// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "atlas_schema_revisions")]
pub struct AtlasSchemaRevision {
    #[sqlx_gen(primary_key, sql_type = "TEXT")]
    pub version: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub description: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "2")]
    #[sqlx(rename = "type")]
    pub atlas_schema_revision_type: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub applied: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub total: i64,
    #[sqlx_gen(sql_type = "DATETIME")]
    pub executed_at: NaiveDateTime,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub execution_time: i64,
    #[sqlx_gen(sql_type = "TEXT")]
    pub error: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub error_stmt: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub hash: String,
    #[sqlx_gen(sql_type = "JSON")]
    pub partial_hashes: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub operator_version: String,
}
