// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "audit_logs")]
pub struct AuditLog {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub user_email: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub user_role: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub action: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub resource_type: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub resource_id: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub resource_name: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub metadata: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub organization_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub user_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
}
