// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "certificates")]
pub struct Certificate {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub name: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub certificate_data: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub private_key: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub certificate_path: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub auto_renew: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub server_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub organization_id: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
