// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "compose_projects")]
pub struct ComposeProject {
    #[sqlx_gen(primary_key, sql_type = "compose_projects_id_enum")]
    pub id: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub name: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub app_name: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub description: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub env_var: Option<String>,
    #[sqlx_gen(sql_type = "TEXT", column_default = "''")]
    pub compose_file: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub refresh_token: Option<String>,
    #[sqlx_gen(
        sql_type = "compose_projects_source_type_enum",
        column_default = "'GITHUB'"
    )]
    pub source_type: String,
    #[sqlx_gen(
        sql_type = "compose_projects_compose_type_enum",
        column_default = "'DOCKER-COMPOSE'"
    )]
    pub compose_type: String,
    #[sqlx_gen(
        sql_type = "compose_projects_compose_status_enum",
        column_default = "'IDLE'"
    )]
    pub compose_status: String,
    #[sqlx_gen(
        sql_type = "compose_projects_trigger_type_enum",
        column_default = "'PUSH'"
    )]
    pub trigger_type: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub repository: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub owner: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub branch: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "1")]
    pub auto_deploy: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub gitlab_project_id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub gitlab_repository: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub gitlab_owner: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub gitlab_branch: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub gitlab_path_namespace: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bitbucket_repository: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bitbucket_repository_slug: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bitbucket_owner: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bitbucket_branch: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub gitea_repository: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub gitea_owner: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub gitea_branch: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub custom_git_url: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub custom_git_branch: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub custom_git_ssh_key_id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT", column_default = "''")]
    pub command: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub enable_submodules: i64,
    #[sqlx_gen(sql_type = "TEXT", column_default = "'./docker-compose.yml'")]
    pub compose_path: String,
    #[sqlx_gen(sql_type = "TEXT", column_default = "''")]
    pub suffix: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub randomize: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub isolated_deployment: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub isolated_deployments_volume: i64,
    #[sqlx_gen(sql_type = "TEXT")]
    pub watch_paths: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub environment_id: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub server_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub github_provider_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub gitlab_provider_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub gitea_provider_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub bitbucket_provider_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
