// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "deployments")]
pub struct Deployment {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub title: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub description: Option<String>,
    #[sqlx_gen(sql_type = "deployments_status_enum", column_default = "'RUNNING'")]
    pub status: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub log_path: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub pid: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub error_message: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub is_preview_deployment: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub started_at: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub finished_at: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub application_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub compose_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub server_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
}
