// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "destinations")]
pub struct Destination {
    #[sqlx_gen(primary_key, sql_type = "destinations_id_enum")]
    pub id: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub name: String,
    #[sqlx_gen(sql_type = "destinations_provider_enum", column_default = "'S3'")]
    pub provider: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub access_key: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub secret_access_key: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bucket: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub region: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub endpoint: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub additional_flags: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub organization_id: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
