// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "libsql_dbs")]
pub struct LibsqlDb {
    #[sqlx_gen(primary_key, sql_type = "libsql_dbs_id_enum")]
    pub id: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub name: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub app_name: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub description: Option<String>,
    #[sqlx_gen(
        sql_type = "TEXT",
        column_default = "'ghcr.io/tursodatabase/libsql-server:latest'"
    )]
    pub docker_image: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub database_user: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub database_password: String,
    #[sqlx_gen(sql_type = "libsql_dbs_sqld_node_enum", column_default = "'PRIMARY'")]
    pub sqld_node: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub sqld_primary_url: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub enable_namespaces: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub external_port: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub external_grpc_port: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub external_admin_port: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub command: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub args: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub env_var: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub memory_reservation: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub memory_limit: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub cpu_reservation: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub cpu_limit: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "1")]
    pub replicas: i64,
    #[sqlx_gen(sql_type = "libsql_dbs_app_status_enum", column_default = "'IDLE'")]
    pub app_status: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub health_check_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub restart_policy_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub placement_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub update_config_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub rollback_config_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub mode_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub labels_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub network_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub endpoint_spec_swarm: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub ulimits_swarm: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub stop_grace_period_swarm: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub environment_id: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub server_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
