// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "notif_ntfy")]
pub struct NotifNtfy {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub server_url: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub topic: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub access_token: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "3")]
    pub priority: i64,
}
