// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "notif_email")]
pub struct NotifEmail {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub smtp_server: String,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub smtp_port: i64,
    #[sqlx_gen(sql_type = "TEXT")]
    pub username: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub password: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub from_address: String,
    #[sqlx_gen(sql_type = "TEXT", column_default = "'[]'")]
    pub to_addresses: String,
}
