// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "notif_pushover")]
pub struct NotifPushover {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub user_key: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub api_token: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub priority: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub retry: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub expire: Option<i64>,
}
