// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "redirects")]
pub struct Redirect {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub regex: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub replacement: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub permanent: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub unique_config_key: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub application_id: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
