// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "servers")]
pub struct Server {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub name: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub description: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub ip_address: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "22")]
    pub port: i64,
    #[sqlx_gen(sql_type = "TEXT", column_default = "'root'")]
    pub username: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub app_name: String,
    #[sqlx_gen(sql_type = "servers_server_status_enum", column_default = "'ACTIVE'")]
    pub server_status: String,
    #[sqlx_gen(sql_type = "servers_server_type_enum", column_default = "'DEPLOY'")]
    pub server_type: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub enable_docker_cleanup: i64,
    #[sqlx_gen(sql_type = "TEXT", column_default = "'0 0 * * *'")]
    pub log_cleanup_cron: Option<String>,
    #[sqlx_gen(sql_type = "TEXT", column_default = "''")]
    pub command: String,
    #[sqlx_gen(sql_type = "TEXT", column_default = "'{}'")]
    pub metrics_config: String,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub ssh_key_id: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
    #[sqlx_gen(sql_type = "TEXT")]
    pub build_memory_limit: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub build_cpu_limit: Option<String>,
}
