// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "settings")]
pub struct Setting {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub server_ip: Option<String>,
    #[sqlx_gen(sql_type = "settings_certificate_type_enum", column_default = "'NONE'")]
    pub certificate_type: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub custom_cert_resolver: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub https: i64,
    #[sqlx_gen(sql_type = "TEXT")]
    pub host: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub lets_encrypt_email: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "1")]
    pub enable_docker_cleanup: i64,
    #[sqlx_gen(sql_type = "TEXT", column_default = "'0 0 * * *'")]
    pub log_cleanup_cron: Option<String>,
    #[sqlx_gen(sql_type = "TEXT", column_default = "''")]
    pub metrics_config: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
