// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq,  Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "two_factor")]
pub struct TwoFactor {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub secret: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub backup_codes: String,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub user_id: i64,
}
