// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

///Enum: main.applications_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "applications_id_enum")]
pub enum ApplicationsIdEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.applications_source_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "applications_source_type_enum")]
pub enum ApplicationsSourceTypeEnum {
    #[sqlx(rename = "DOCKER")]
    Docker,

    #[sqlx(rename = "GIT")]
    Git,

    #[sqlx(rename = "GITHUB")]
    Github,

    #[sqlx(rename = "GITLAB")]
    Gitlab,

    #[sqlx(rename = "BITBUCKET")]
    Bitbucket,

    #[sqlx(rename = "GITEA")]
    Gitea,

    #[sqlx(rename = "DROP")]
    Drop,
}
///Enum: main.applications_build_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "applications_build_type_enum")]
pub enum ApplicationsBuildTypeEnum {
    #[sqlx(rename = "DOCKERFILE")]
    Dockerfile,

    #[sqlx(rename = "HEROKU_BUILDPACKS")]
    HerokuBuildpacks,

    #[sqlx(rename = "PAKETO_BUILDPACKS")]
    PaketoBuildpacks,

    #[sqlx(rename = "NIXPACKS")]
    Nixpacks,

    #[sqlx(rename = "STATIC")]
    Static,

    #[sqlx(rename = "RAILPACK")]
    Railpack,
}
///Enum: main.applications_app_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "applications_app_status_enum")]
pub enum ApplicationsAppStatusEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.applications_trigger_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "applications_trigger_type_enum"
)]
pub enum ApplicationsTriggerTypeEnum {
    #[sqlx(rename = "PUSH")]
    Push,

    #[sqlx(rename = "TAG")]
    Tag,
}
///Enum: main.applications_dockerfile_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "applications_dockerfile_enum")]
pub enum ApplicationsDockerfileEnum {
    #[sqlx(rename = "DOCKERFILE")]
    Dockerfile,

    #[sqlx(rename = "HEROKU_BUILDPACKS")]
    HerokuBuildpacks,

    #[sqlx(rename = "PAKETO_BUILDPACKS")]
    PaketoBuildpacks,

    #[sqlx(rename = "NIXPACKS")]
    Nixpacks,

    #[sqlx(rename = "STATIC")]
    Static,

    #[sqlx(rename = "RAILPACK")]
    Railpack,
}
///Enum: main.applications_preview_certificate_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "applications_preview_certificate_type_enum"
)]
pub enum ApplicationsPreviewCertificateTypeEnum {
    #[sqlx(rename = "LETSENCRYPT")]
    Letsencrypt,

    #[sqlx(rename = "NONE")]
    None,

    #[sqlx(rename = "CUSTOM")]
    Custom,
}
///Enum: main.backups_backup_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "backups_backup_type_enum")]
pub enum BackupsBackupTypeEnum {
    #[sqlx(rename = "DATABASE")]
    Database,

    #[sqlx(rename = "COMPOSE")]
    Compose,
}
///Enum: main.backups_database_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "backups_database_type_enum")]
pub enum BackupsDatabaseTypeEnum {
    #[sqlx(rename = "POSTGRES")]
    Postgres,

    #[sqlx(rename = "MARIADB")]
    Mariadb,

    #[sqlx(rename = "MYSQL")]
    Mysql,

    #[sqlx(rename = "MONGO")]
    Mongo,

    #[sqlx(rename = "REDIS")]
    Redis,

    #[sqlx(rename = "LIBSQL")]
    Libsql,
}
///Enum: main.compose_projects_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "compose_projects_id_enum")]
pub enum ComposeProjectsIdEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.compose_projects_source_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "compose_projects_source_type_enum"
)]
pub enum ComposeProjectsSourceTypeEnum {
    #[sqlx(rename = "GIT")]
    Git,

    #[sqlx(rename = "GITHUB")]
    Github,

    #[sqlx(rename = "GITLAB")]
    Gitlab,

    #[sqlx(rename = "BITBUCKET")]
    Bitbucket,

    #[sqlx(rename = "GITEA")]
    Gitea,

    #[sqlx(rename = "RAW")]
    Raw,
}
///Enum: main.compose_projects_compose_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "compose_projects_compose_type_enum"
)]
pub enum ComposeProjectsComposeTypeEnum {
    #[sqlx(rename = "DOCKER-COMPOSE")]
    DockerCompose,

    #[sqlx(rename = "STACK")]
    Stack,
}
///Enum: main.compose_projects_compose_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "compose_projects_compose_status_enum"
)]
pub enum ComposeProjectsComposeStatusEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.compose_projects_trigger_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "compose_projects_trigger_type_enum"
)]
pub enum ComposeProjectsTriggerTypeEnum {
    #[sqlx(rename = "PUSH")]
    Push,

    #[sqlx(rename = "TAG")]
    Tag,
}
///Enum: main.deployments_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "deployments_status_enum")]
pub enum DeploymentsStatusEnum {
    #[sqlx(rename = "QUEUED")]
    Queued,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,

    #[sqlx(rename = "CANCELLED")]
    Cancelled,
}
///Enum: main.destinations_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "destinations_id_enum")]
pub enum DestinationsIdEnum {
    S3,
    R2,

    #[sqlx(rename = "BACKBLAZE")]
    Backblaze,

    #[sqlx(rename = "GCS")]
    Gcs,

    #[sqlx(rename = "DO_SPACES")]
    DoSpaces,
}
///Enum: main.destinations_provider_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "destinations_provider_enum")]
pub enum DestinationsProviderEnum {
    S3,
    R2,

    #[sqlx(rename = "BACKBLAZE")]
    Backblaze,

    #[sqlx(rename = "GCS")]
    Gcs,

    #[sqlx(rename = "DO_SPACES")]
    DoSpaces,
}
///Enum: main.domains_domain_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "domains_domain_type_enum")]
pub enum DomainsDomainTypeEnum {
    #[sqlx(rename = "APPLICATION")]
    Application,

    #[sqlx(rename = "COMPOSE")]
    Compose,

    #[sqlx(rename = "PREVIEW")]
    Preview,
}
///Enum: main.domains_certificate_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "domains_certificate_type_enum")]
pub enum DomainsCertificateTypeEnum {
    #[sqlx(rename = "LETSENCRYPT")]
    Letsencrypt,

    #[sqlx(rename = "NONE")]
    None,

    #[sqlx(rename = "CUSTOM")]
    Custom,
}
///Enum: main.git_providers_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "git_providers_id_enum")]
pub enum GitProvidersIdEnum {
    #[sqlx(rename = "GITHUB")]
    Github,

    #[sqlx(rename = "GITLAB")]
    Gitlab,

    #[sqlx(rename = "GITEA")]
    Gitea,

    #[sqlx(rename = "BITBUCKET")]
    Bitbucket,
}
///Enum: main.git_providers_provider_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "git_providers_provider_type_enum"
)]
pub enum GitProvidersProviderTypeEnum {
    #[sqlx(rename = "GITHUB")]
    Github,

    #[sqlx(rename = "GITLAB")]
    Gitlab,

    #[sqlx(rename = "GITEA")]
    Gitea,

    #[sqlx(rename = "BITBUCKET")]
    Bitbucket,
}
///Enum: main.jwt_tokens_role_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "jwt_tokens_role_enum")]
pub enum JwtTokensRoleEnum {
    #[sqlx(rename = "OWNER")]
    Owner,

    #[sqlx(rename = "ADMIN")]
    Admin,

    #[sqlx(rename = "MEMBER")]
    Member,
}
///Enum: main.libsql_dbs_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "libsql_dbs_id_enum")]
pub enum LibsqlDbsIdEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.libsql_dbs_sqld_node_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "libsql_dbs_sqld_node_enum")]
pub enum LibsqlDbsSqldNodeEnum {
    #[sqlx(rename = "PRIMARY")]
    Primary,

    #[sqlx(rename = "REPLICA")]
    Replica,
}
///Enum: main.libsql_dbs_app_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "libsql_dbs_app_status_enum")]
pub enum LibsqlDbsAppStatusEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.mariadb_dbs_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "mariadb_dbs_id_enum")]
pub enum MariadbDbsIdEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.mariadb_dbs_app_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "mariadb_dbs_app_status_enum")]
pub enum MariadbDbsAppStatusEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.mongo_dbs_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "mongo_dbs_id_enum")]
pub enum MongoDbsIdEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.mongo_dbs_app_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "mongo_dbs_app_status_enum")]
pub enum MongoDbsAppStatusEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.mounts_mount_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "mounts_mount_type_enum")]
pub enum MountsMountTypeEnum {
    #[sqlx(rename = "BIND")]
    Bind,

    #[sqlx(rename = "VOLUME")]
    Volume,

    #[sqlx(rename = "FILE")]
    File,
}
///Enum: main.mounts_service_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "mounts_service_type_enum")]
pub enum MountsServiceTypeEnum {
    #[sqlx(rename = "APPLICATION")]
    Application,

    #[sqlx(rename = "COMPOSE")]
    Compose,

    #[sqlx(rename = "POSTGRES")]
    Postgres,

    #[sqlx(rename = "MYSQL")]
    Mysql,

    #[sqlx(rename = "MARIADB")]
    Mariadb,

    #[sqlx(rename = "MONGO")]
    Mongo,

    #[sqlx(rename = "REDIS")]
    Redis,

    #[sqlx(rename = "LIBSQL")]
    Libsql,
}
///Enum: main.mysql_dbs_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "mysql_dbs_id_enum")]
pub enum MysqlDbsIdEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.mysql_dbs_app_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "mysql_dbs_app_status_enum")]
pub enum MysqlDbsAppStatusEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.notifications_notification_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "notifications_notification_type_enum"
)]
pub enum NotificationsNotificationTypeEnum {
    #[sqlx(rename = "SLACK")]
    Slack,

    #[sqlx(rename = "TELEGRAM")]
    Telegram,

    #[sqlx(rename = "DISCORD")]
    Discord,

    #[sqlx(rename = "EMAIL")]
    Email,

    #[sqlx(rename = "RESEND")]
    Resend,

    #[sqlx(rename = "GOTIFY")]
    Gotify,

    #[sqlx(rename = "NTFY")]
    Ntfy,

    #[sqlx(rename = "MATTERMOST")]
    Mattermost,

    #[sqlx(rename = "PUSHOVER")]
    Pushover,

    #[sqlx(rename = "CUSTOM")]
    Custom,

    #[sqlx(rename = "LARK")]
    Lark,

    #[sqlx(rename = "TEAMS")]
    Teams,
}
///Enum: main.organization_invites_role_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "organization_invites_role_enum"
)]
pub enum OrganizationInvitesRoleEnum {
    #[sqlx(rename = "ADMIN")]
    Admin,

    #[sqlx(rename = "MEMBER")]
    Member,
}
///Enum: main.organization_invites_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "organization_invites_status_enum"
)]
pub enum OrganizationInvitesStatusEnum {
    #[sqlx(rename = "PENDING")]
    Pending,

    #[sqlx(rename = "ACCEPTED")]
    Accepted,

    #[sqlx(rename = "REJECTED")]
    Rejected,
}
///Enum: main.organization_members_role_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "organization_members_role_enum"
)]
pub enum OrganizationMembersRoleEnum {
    #[sqlx(rename = "ADMIN")]
    Admin,

    #[sqlx(rename = "MEMBER")]
    Member,
}
///Enum: main.patches_patch_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "patches_patch_type_enum")]
pub enum PatchesPatchTypeEnum {
    #[sqlx(rename = "CREATE")]
    Create,

    #[sqlx(rename = "UPDATE")]
    Update,

    #[sqlx(rename = "DELETE")]
    Delete,
}
///Enum: main.ports_protocol_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "ports_protocol_enum")]
pub enum PortsProtocolEnum {
    #[sqlx(rename = "TCP")]
    Tcp,

    #[sqlx(rename = "UDP")]
    Udp,
}
///Enum: main.ports_publish_mode_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "ports_publish_mode_enum")]
pub enum PortsPublishModeEnum {
    #[sqlx(rename = "INGRESS")]
    Ingress,

    #[sqlx(rename = "HOST")]
    Host,
}
///Enum: main.postgres_dbs_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "postgres_dbs_id_enum")]
pub enum PostgresDbsIdEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.postgres_dbs_app_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "postgres_dbs_app_status_enum")]
pub enum PostgresDbsAppStatusEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.redis_dbs_id_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "redis_dbs_id_enum")]
pub enum RedisDbsIdEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.redis_dbs_app_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "redis_dbs_app_status_enum")]
pub enum RedisDbsAppStatusEnum {
    #[sqlx(rename = "IDLE")]
    Idle,

    #[sqlx(rename = "RUNNING")]
    Running,

    #[sqlx(rename = "DONE")]
    Done,

    #[sqlx(rename = "ERROR")]
    Error,
}
///Enum: main.registries_registry_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "registries_registry_type_enum")]
pub enum RegistriesRegistryTypeEnum {
    #[sqlx(rename = "CLOUD")]
    Cloud,

    #[sqlx(rename = "SELF_HOSTED")]
    SelfHosted,
}
///Enum: main.schedules_shell_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "schedules_shell_type_enum")]
pub enum SchedulesShellTypeEnum {
    #[sqlx(rename = "BASH")]
    Bash,

    #[sqlx(rename = "SH")]
    Sh,
}
///Enum: main.schedules_schedule_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "schedules_schedule_type_enum")]
pub enum SchedulesScheduleTypeEnum {
    #[sqlx(rename = "APPLICATION")]
    Application,

    #[sqlx(rename = "COMPOSE")]
    Compose,

    #[sqlx(rename = "SERVER")]
    Server,

    #[sqlx(rename = "DOKPANEL-SERVER")]
    DokpanelServer,
}
///Enum: main.schedules_schedule_action_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "schedules_schedule_action_enum"
)]
pub enum SchedulesScheduleActionEnum {
    #[sqlx(rename = "EXEC")]
    Exec,

    #[sqlx(rename = "DEPLOY")]
    Deploy,

    #[sqlx(rename = "REDEPLOY")]
    Redeploy,

    #[sqlx(rename = "REBUILD")]
    Rebuild,

    #[sqlx(rename = "RELOAD")]
    Reload,

    #[sqlx(rename = "START")]
    Start,

    #[sqlx(rename = "STOP")]
    Stop,
}
///Enum: main.servers_server_status_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "servers_server_status_enum")]
pub enum ServersServerStatusEnum {
    #[sqlx(rename = "ACTIVE")]
    Active,

    #[sqlx(rename = "INACTIVE")]
    Inactive,
}
///Enum: main.servers_server_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "servers_server_type_enum")]
pub enum ServersServerTypeEnum {
    #[sqlx(rename = "DEPLOY")]
    Deploy,

    #[sqlx(rename = "BUILD")]
    Build,
}
///Enum: main.settings_certificate_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "settings_certificate_type_enum"
)]
pub enum SettingsCertificateTypeEnum {
    #[sqlx(rename = "NONE")]
    None,

    #[sqlx(rename = "LETSENCRYPT")]
    Letsencrypt,

    #[sqlx(rename = "CUSTOM")]
    Custom,
}
///Enum: main.users_role_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(kind = "enum", schema = "main", name = "users_role_enum")]
pub enum UsersRoleEnum {
    #[sqlx(rename = "OWNER")]
    Owner,

    #[sqlx(rename = "ADMIN")]
    Admin,

    #[sqlx(rename = "MEMBER")]
    Member,
}
///Enum: main.volume_backups_service_type_enum
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, SqlxGen)]
#[sqlx_gen(
    kind = "enum",
    schema = "main",
    name = "volume_backups_service_type_enum"
)]
pub enum VolumeBackupsServiceTypeEnum {
    #[sqlx(rename = "APPLICATION")]
    Application,

    #[sqlx(rename = "COMPOSE")]
    Compose,

    #[sqlx(rename = "POSTGRES")]
    Postgres,

    #[sqlx(rename = "MYSQL")]
    Mysql,

    #[sqlx(rename = "MARIADB")]
    Mariadb,

    #[sqlx(rename = "MONGO")]
    Mongo,

    #[sqlx(rename = "REDIS")]
    Redis,

    #[sqlx(rename = "LIBSQL")]
    Libsql,
}
