// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "users")]
pub struct User {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub email: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub last_name: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub first_name: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub avatar: String,
    #[sqlx_gen(sql_type = "users_role_enum", column_default = "'OWNER'")]
    pub role: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub about_me: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub password: String,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub is_email_verify: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub email_verify_at: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub two_factor_enable: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub is_registered: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "NULL")]
    pub added_by: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub group_id: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
