// Auto-generated by sqlx-gen. Do not edit.

use crate::models::ai_settings::AiSetting;

#[derive(Debug, Clone, Default)]
pub struct PaginateAiSettingParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationAiSettingMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedAiSetting {
    pub meta: PaginationAiSettingMeta,
    pub data: Vec<AiSetting>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertAiSettingParams {
    pub name: String,
    pub api_url: String,
    pub api_key: String,
    pub model: String,
    pub is_enabled: Option<i64>,
    pub organization_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteAiSettingParams {
    pub name: String,
    pub api_url: String,
    pub api_key: String,
    pub model: String,
    pub is_enabled: i64,
    pub organization_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateAiSettingParams {
    pub name: Option<String>,
    pub api_url: Option<String>,
    pub api_key: Option<String>,
    pub model: Option<String>,
    pub is_enabled: Option<i64>,
    pub organization_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct AiSettingRepository {
    pool: sqlx::SqlitePool,
}

impl AiSettingRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<AiSetting>, sqlx::Error> {
        sqlx::query_as::<_, AiSetting>(r#"SELECT * FROM ai_settings"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateAiSettingParams,
    ) -> Result<PaginatedAiSetting, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM ai_settings"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, AiSetting>(
            r#"
            SELECT *
            FROM ai_settings
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedAiSetting {
            meta: PaginationAiSettingMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<AiSetting>, sqlx::Error> {
        sqlx::query_as::<_, AiSetting>(
            r#"
            SELECT *
            FROM ai_settings
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertAiSettingParams) -> Result<AiSetting, sqlx::Error> {
        sqlx::query_as::<
            _,
            AiSetting,
        >(
                r#"
            INSERT INTO ai_settings (name, api_url, api_key, model, is_enabled, organization_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, COALESCE(?, 1), ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.api_url)
            .bind(&params.api_key)
            .bind(&params.model)
            .bind(&params.is_enabled)
            .bind(&params.organization_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertAiSettingParams>,
    ) -> Result<Vec<AiSetting>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 8usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 8usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "1"),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "ai_settings",
                "name, api_url, api_key, model, is_enabled, organization_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, AiSetting>(&sql);
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.api_url);
                query = query.bind(&params.api_key);
                query = query.bind(&params.model);
                query = query.bind(&params.is_enabled);
                query = query.bind(&params.organization_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteAiSettingParams,
    ) -> Result<AiSetting, sqlx::Error> {
        sqlx::query_as::<_, AiSetting>(
            r#"
            UPDATE ai_settings
            SET
              name = ?,
              api_url = ?,
              api_key = ?,
              model = ?,
              is_enabled = ?,
              organization_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.api_url)
        .bind(&params.api_key)
        .bind(&params.model)
        .bind(&params.is_enabled)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateAiSettingParams,
    ) -> Result<AiSetting, sqlx::Error> {
        sqlx::query_as::<_, AiSetting>(
            r#"
            UPDATE ai_settings
            SET
              name = COALESCE(?, name),
              api_url = COALESCE(?, api_url),
              api_key = COALESCE(?, api_key),
              model = COALESCE(?, model),
              is_enabled = COALESCE(?, is_enabled),
              organization_id = COALESCE(?, organization_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.api_url)
        .bind(&params.api_key)
        .bind(&params.model)
        .bind(&params.is_enabled)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM ai_settings
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
