// Auto-generated by sqlx-gen. Do not edit.

use crate::models::compose_projects::ComposeProject;

#[derive(Debug, Clone, Default)]
pub struct PaginateComposeProjectParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationComposeProjectMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedComposeProject {
    pub meta: PaginationComposeProjectMeta,
    pub data: Vec<ComposeProject>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertComposeProjectParams {
    pub name: String,
    pub app_name: String,
    pub description: Option<String>,
    pub env_var: Option<String>,
    pub compose_file: Option<String>,
    pub refresh_token: Option<String>,
    pub source_type: Option<String>,
    pub compose_type: Option<String>,
    pub compose_status: Option<String>,
    pub trigger_type: Option<String>,
    pub repository: Option<String>,
    pub owner: Option<String>,
    pub branch: Option<String>,
    pub auto_deploy: Option<i64>,
    pub gitlab_project_id: Option<i64>,
    pub gitlab_repository: Option<String>,
    pub gitlab_owner: Option<String>,
    pub gitlab_branch: Option<String>,
    pub gitlab_path_namespace: Option<String>,
    pub bitbucket_repository: Option<String>,
    pub bitbucket_repository_slug: Option<String>,
    pub bitbucket_owner: Option<String>,
    pub bitbucket_branch: Option<String>,
    pub gitea_repository: Option<String>,
    pub gitea_owner: Option<String>,
    pub gitea_branch: Option<String>,
    pub custom_git_url: Option<String>,
    pub custom_git_branch: Option<String>,
    pub custom_git_ssh_key_id: Option<i64>,
    pub command: Option<String>,
    pub enable_submodules: Option<i64>,
    pub compose_path: Option<String>,
    pub suffix: Option<String>,
    pub randomize: Option<i64>,
    pub isolated_deployment: Option<i64>,
    pub isolated_deployments_volume: Option<i64>,
    pub watch_paths: Option<String>,
    pub environment_id: i64,
    pub server_id: Option<i64>,
    pub github_provider_id: Option<i64>,
    pub gitlab_provider_id: Option<i64>,
    pub gitea_provider_id: Option<i64>,
    pub bitbucket_provider_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteComposeProjectParams {
    pub name: String,
    pub app_name: String,
    pub description: Option<String>,
    pub env_var: Option<String>,
    pub compose_file: String,
    pub refresh_token: Option<String>,
    pub source_type: String,
    pub compose_type: String,
    pub compose_status: String,
    pub trigger_type: String,
    pub repository: Option<String>,
    pub owner: Option<String>,
    pub branch: Option<String>,
    pub auto_deploy: i64,
    pub gitlab_project_id: Option<i64>,
    pub gitlab_repository: Option<String>,
    pub gitlab_owner: Option<String>,
    pub gitlab_branch: Option<String>,
    pub gitlab_path_namespace: Option<String>,
    pub bitbucket_repository: Option<String>,
    pub bitbucket_repository_slug: Option<String>,
    pub bitbucket_owner: Option<String>,
    pub bitbucket_branch: Option<String>,
    pub gitea_repository: Option<String>,
    pub gitea_owner: Option<String>,
    pub gitea_branch: Option<String>,
    pub custom_git_url: Option<String>,
    pub custom_git_branch: Option<String>,
    pub custom_git_ssh_key_id: Option<i64>,
    pub command: String,
    pub enable_submodules: i64,
    pub compose_path: String,
    pub suffix: String,
    pub randomize: i64,
    pub isolated_deployment: i64,
    pub isolated_deployments_volume: i64,
    pub watch_paths: Option<String>,
    pub environment_id: i64,
    pub server_id: Option<i64>,
    pub github_provider_id: Option<i64>,
    pub gitlab_provider_id: Option<i64>,
    pub gitea_provider_id: Option<i64>,
    pub bitbucket_provider_id: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateComposeProjectParams {
    pub name: Option<String>,
    pub app_name: Option<String>,
    pub description: Option<String>,
    pub env_var: Option<String>,
    pub compose_file: Option<String>,
    pub refresh_token: Option<String>,
    pub source_type: Option<String>,
    pub compose_type: Option<String>,
    pub compose_status: Option<String>,
    pub trigger_type: Option<String>,
    pub repository: Option<String>,
    pub owner: Option<String>,
    pub branch: Option<String>,
    pub auto_deploy: Option<i64>,
    pub gitlab_project_id: Option<i64>,
    pub gitlab_repository: Option<String>,
    pub gitlab_owner: Option<String>,
    pub gitlab_branch: Option<String>,
    pub gitlab_path_namespace: Option<String>,
    pub bitbucket_repository: Option<String>,
    pub bitbucket_repository_slug: Option<String>,
    pub bitbucket_owner: Option<String>,
    pub bitbucket_branch: Option<String>,
    pub gitea_repository: Option<String>,
    pub gitea_owner: Option<String>,
    pub gitea_branch: Option<String>,
    pub custom_git_url: Option<String>,
    pub custom_git_branch: Option<String>,
    pub custom_git_ssh_key_id: Option<i64>,
    pub command: Option<String>,
    pub enable_submodules: Option<i64>,
    pub compose_path: Option<String>,
    pub suffix: Option<String>,
    pub randomize: Option<i64>,
    pub isolated_deployment: Option<i64>,
    pub isolated_deployments_volume: Option<i64>,
    pub watch_paths: Option<String>,
    pub environment_id: Option<i64>,
    pub server_id: Option<i64>,
    pub github_provider_id: Option<i64>,
    pub gitlab_provider_id: Option<i64>,
    pub gitea_provider_id: Option<i64>,
    pub bitbucket_provider_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct ComposeProjectRepository {
    pool: sqlx::SqlitePool,
}

impl ComposeProjectRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<ComposeProject>, sqlx::Error> {
        sqlx::query_as::<_, ComposeProject>(r#"SELECT * FROM compose_projects"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateComposeProjectParams,
    ) -> Result<PaginatedComposeProject, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM compose_projects"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, ComposeProject>(
            r#"
            SELECT *
            FROM compose_projects
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedComposeProject {
            meta: PaginationComposeProjectMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: String) -> Result<Option<ComposeProject>, sqlx::Error> {
        sqlx::query_as::<_, ComposeProject>(
            r#"
            SELECT *
            FROM compose_projects
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertComposeProjectParams,
    ) -> Result<ComposeProject, sqlx::Error> {
        sqlx::query_as::<
            _,
            ComposeProject,
        >(
                r#"
            INSERT INTO compose_projects (name, app_name, description, env_var, compose_file, refresh_token, source_type, compose_type, compose_status, trigger_type, repository, owner, branch, auto_deploy, gitlab_project_id, gitlab_repository, gitlab_owner, gitlab_branch, gitlab_path_namespace, bitbucket_repository, bitbucket_repository_slug, bitbucket_owner, bitbucket_branch, gitea_repository, gitea_owner, gitea_branch, custom_git_url, custom_git_branch, custom_git_ssh_key_id, command, enable_submodules, compose_path, suffix, randomize, isolated_deployment, isolated_deployments_volume, watch_paths, environment_id, server_id, github_provider_id, gitlab_provider_id, gitea_provider_id, bitbucket_provider_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, COALESCE(?, ''), ?, COALESCE(?, 'GITHUB'), COALESCE(?, 'DOCKER-COMPOSE'), COALESCE(?, 'IDLE'), COALESCE(?, 'PUSH'), ?, ?, ?, COALESCE(?, 1), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, ''), COALESCE(?, 0), COALESCE(?, './docker-compose.yml'), COALESCE(?, ''), COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, 0), ?, ?, ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.app_name)
            .bind(&params.description)
            .bind(&params.env_var)
            .bind(&params.compose_file)
            .bind(&params.refresh_token)
            .bind(&params.source_type)
            .bind(&params.compose_type)
            .bind(&params.compose_status)
            .bind(&params.trigger_type)
            .bind(&params.repository)
            .bind(&params.owner)
            .bind(&params.branch)
            .bind(&params.auto_deploy)
            .bind(&params.gitlab_project_id)
            .bind(&params.gitlab_repository)
            .bind(&params.gitlab_owner)
            .bind(&params.gitlab_branch)
            .bind(&params.gitlab_path_namespace)
            .bind(&params.bitbucket_repository)
            .bind(&params.bitbucket_repository_slug)
            .bind(&params.bitbucket_owner)
            .bind(&params.bitbucket_branch)
            .bind(&params.gitea_repository)
            .bind(&params.gitea_owner)
            .bind(&params.gitea_branch)
            .bind(&params.custom_git_url)
            .bind(&params.custom_git_branch)
            .bind(&params.custom_git_ssh_key_id)
            .bind(&params.command)
            .bind(&params.enable_submodules)
            .bind(&params.compose_path)
            .bind(&params.suffix)
            .bind(&params.randomize)
            .bind(&params.isolated_deployment)
            .bind(&params.isolated_deployments_volume)
            .bind(&params.watch_paths)
            .bind(&params.environment_id)
            .bind(&params.server_id)
            .bind(&params.github_provider_id)
            .bind(&params.gitlab_provider_id)
            .bind(&params.gitea_provider_id)
            .bind(&params.bitbucket_provider_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertComposeProjectParams>,
    ) -> Result<Vec<ComposeProject>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 45usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 45usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "''"),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'GITHUB'"),
                    format!("COALESCE(?, {})", "'DOCKER-COMPOSE'"),
                    format!("COALESCE(?, {})", "'IDLE'"),
                    format!("COALESCE(?, {})", "'PUSH'"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "1"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "''"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "'./docker-compose.yml'"),
                    format!("COALESCE(?, {})", "''"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "compose_projects",
                "name, app_name, description, env_var, compose_file, refresh_token, source_type, compose_type, compose_status, trigger_type, repository, owner, branch, auto_deploy, gitlab_project_id, gitlab_repository, gitlab_owner, gitlab_branch, gitlab_path_namespace, bitbucket_repository, bitbucket_repository_slug, bitbucket_owner, bitbucket_branch, gitea_repository, gitea_owner, gitea_branch, custom_git_url, custom_git_branch, custom_git_ssh_key_id, command, enable_submodules, compose_path, suffix, randomize, isolated_deployment, isolated_deployments_volume, watch_paths, environment_id, server_id, github_provider_id, gitlab_provider_id, gitea_provider_id, bitbucket_provider_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, ComposeProject>(&sql);
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.app_name);
                query = query.bind(&params.description);
                query = query.bind(&params.env_var);
                query = query.bind(&params.compose_file);
                query = query.bind(&params.refresh_token);
                query = query.bind(&params.source_type);
                query = query.bind(&params.compose_type);
                query = query.bind(&params.compose_status);
                query = query.bind(&params.trigger_type);
                query = query.bind(&params.repository);
                query = query.bind(&params.owner);
                query = query.bind(&params.branch);
                query = query.bind(&params.auto_deploy);
                query = query.bind(&params.gitlab_project_id);
                query = query.bind(&params.gitlab_repository);
                query = query.bind(&params.gitlab_owner);
                query = query.bind(&params.gitlab_branch);
                query = query.bind(&params.gitlab_path_namespace);
                query = query.bind(&params.bitbucket_repository);
                query = query.bind(&params.bitbucket_repository_slug);
                query = query.bind(&params.bitbucket_owner);
                query = query.bind(&params.bitbucket_branch);
                query = query.bind(&params.gitea_repository);
                query = query.bind(&params.gitea_owner);
                query = query.bind(&params.gitea_branch);
                query = query.bind(&params.custom_git_url);
                query = query.bind(&params.custom_git_branch);
                query = query.bind(&params.custom_git_ssh_key_id);
                query = query.bind(&params.command);
                query = query.bind(&params.enable_submodules);
                query = query.bind(&params.compose_path);
                query = query.bind(&params.suffix);
                query = query.bind(&params.randomize);
                query = query.bind(&params.isolated_deployment);
                query = query.bind(&params.isolated_deployments_volume);
                query = query.bind(&params.watch_paths);
                query = query.bind(&params.environment_id);
                query = query.bind(&params.server_id);
                query = query.bind(&params.github_provider_id);
                query = query.bind(&params.gitlab_provider_id);
                query = query.bind(&params.gitea_provider_id);
                query = query.bind(&params.bitbucket_provider_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: String,
        params: &OverwriteComposeProjectParams,
    ) -> Result<ComposeProject, sqlx::Error> {
        sqlx::query_as::<_, ComposeProject>(
            r#"
            UPDATE compose_projects
            SET
              name = ?,
              app_name = ?,
              description = ?,
              env_var = ?,
              compose_file = ?,
              refresh_token = ?,
              source_type = ?,
              compose_type = ?,
              compose_status = ?,
              trigger_type = ?,
              repository = ?,
              owner = ?,
              branch = ?,
              auto_deploy = ?,
              gitlab_project_id = ?,
              gitlab_repository = ?,
              gitlab_owner = ?,
              gitlab_branch = ?,
              gitlab_path_namespace = ?,
              bitbucket_repository = ?,
              bitbucket_repository_slug = ?,
              bitbucket_owner = ?,
              bitbucket_branch = ?,
              gitea_repository = ?,
              gitea_owner = ?,
              gitea_branch = ?,
              custom_git_url = ?,
              custom_git_branch = ?,
              custom_git_ssh_key_id = ?,
              command = ?,
              enable_submodules = ?,
              compose_path = ?,
              suffix = ?,
              randomize = ?,
              isolated_deployment = ?,
              isolated_deployments_volume = ?,
              watch_paths = ?,
              environment_id = ?,
              server_id = ?,
              github_provider_id = ?,
              gitlab_provider_id = ?,
              gitea_provider_id = ?,
              bitbucket_provider_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.app_name)
        .bind(&params.description)
        .bind(&params.env_var)
        .bind(&params.compose_file)
        .bind(&params.refresh_token)
        .bind(&params.source_type)
        .bind(&params.compose_type)
        .bind(&params.compose_status)
        .bind(&params.trigger_type)
        .bind(&params.repository)
        .bind(&params.owner)
        .bind(&params.branch)
        .bind(&params.auto_deploy)
        .bind(&params.gitlab_project_id)
        .bind(&params.gitlab_repository)
        .bind(&params.gitlab_owner)
        .bind(&params.gitlab_branch)
        .bind(&params.gitlab_path_namespace)
        .bind(&params.bitbucket_repository)
        .bind(&params.bitbucket_repository_slug)
        .bind(&params.bitbucket_owner)
        .bind(&params.bitbucket_branch)
        .bind(&params.gitea_repository)
        .bind(&params.gitea_owner)
        .bind(&params.gitea_branch)
        .bind(&params.custom_git_url)
        .bind(&params.custom_git_branch)
        .bind(&params.custom_git_ssh_key_id)
        .bind(&params.command)
        .bind(&params.enable_submodules)
        .bind(&params.compose_path)
        .bind(&params.suffix)
        .bind(&params.randomize)
        .bind(&params.isolated_deployment)
        .bind(&params.isolated_deployments_volume)
        .bind(&params.watch_paths)
        .bind(&params.environment_id)
        .bind(&params.server_id)
        .bind(&params.github_provider_id)
        .bind(&params.gitlab_provider_id)
        .bind(&params.gitea_provider_id)
        .bind(&params.bitbucket_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: String,
        params: &UpdateComposeProjectParams,
    ) -> Result<ComposeProject, sqlx::Error> {
        sqlx::query_as::<_, ComposeProject>(
            r#"
            UPDATE compose_projects
            SET
              name = COALESCE(?, name),
              app_name = COALESCE(?, app_name),
              description = COALESCE(?, description),
              env_var = COALESCE(?, env_var),
              compose_file = COALESCE(?, compose_file),
              refresh_token = COALESCE(?, refresh_token),
              source_type = COALESCE(?, source_type),
              compose_type = COALESCE(?, compose_type),
              compose_status = COALESCE(?, compose_status),
              trigger_type = COALESCE(?, trigger_type),
              repository = COALESCE(?, repository),
              owner = COALESCE(?, owner),
              branch = COALESCE(?, branch),
              auto_deploy = COALESCE(?, auto_deploy),
              gitlab_project_id = COALESCE(?, gitlab_project_id),
              gitlab_repository = COALESCE(?, gitlab_repository),
              gitlab_owner = COALESCE(?, gitlab_owner),
              gitlab_branch = COALESCE(?, gitlab_branch),
              gitlab_path_namespace = COALESCE(?, gitlab_path_namespace),
              bitbucket_repository = COALESCE(?, bitbucket_repository),
              bitbucket_repository_slug = COALESCE(?, bitbucket_repository_slug),
              bitbucket_owner = COALESCE(?, bitbucket_owner),
              bitbucket_branch = COALESCE(?, bitbucket_branch),
              gitea_repository = COALESCE(?, gitea_repository),
              gitea_owner = COALESCE(?, gitea_owner),
              gitea_branch = COALESCE(?, gitea_branch),
              custom_git_url = COALESCE(?, custom_git_url),
              custom_git_branch = COALESCE(?, custom_git_branch),
              custom_git_ssh_key_id = COALESCE(?, custom_git_ssh_key_id),
              command = COALESCE(?, command),
              enable_submodules = COALESCE(?, enable_submodules),
              compose_path = COALESCE(?, compose_path),
              suffix = COALESCE(?, suffix),
              randomize = COALESCE(?, randomize),
              isolated_deployment = COALESCE(?, isolated_deployment),
              isolated_deployments_volume = COALESCE(?, isolated_deployments_volume),
              watch_paths = COALESCE(?, watch_paths),
              environment_id = COALESCE(?, environment_id),
              server_id = COALESCE(?, server_id),
              github_provider_id = COALESCE(?, github_provider_id),
              gitlab_provider_id = COALESCE(?, gitlab_provider_id),
              gitea_provider_id = COALESCE(?, gitea_provider_id),
              bitbucket_provider_id = COALESCE(?, bitbucket_provider_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.app_name)
        .bind(&params.description)
        .bind(&params.env_var)
        .bind(&params.compose_file)
        .bind(&params.refresh_token)
        .bind(&params.source_type)
        .bind(&params.compose_type)
        .bind(&params.compose_status)
        .bind(&params.trigger_type)
        .bind(&params.repository)
        .bind(&params.owner)
        .bind(&params.branch)
        .bind(&params.auto_deploy)
        .bind(&params.gitlab_project_id)
        .bind(&params.gitlab_repository)
        .bind(&params.gitlab_owner)
        .bind(&params.gitlab_branch)
        .bind(&params.gitlab_path_namespace)
        .bind(&params.bitbucket_repository)
        .bind(&params.bitbucket_repository_slug)
        .bind(&params.bitbucket_owner)
        .bind(&params.bitbucket_branch)
        .bind(&params.gitea_repository)
        .bind(&params.gitea_owner)
        .bind(&params.gitea_branch)
        .bind(&params.custom_git_url)
        .bind(&params.custom_git_branch)
        .bind(&params.custom_git_ssh_key_id)
        .bind(&params.command)
        .bind(&params.enable_submodules)
        .bind(&params.compose_path)
        .bind(&params.suffix)
        .bind(&params.randomize)
        .bind(&params.isolated_deployment)
        .bind(&params.isolated_deployments_volume)
        .bind(&params.watch_paths)
        .bind(&params.environment_id)
        .bind(&params.server_id)
        .bind(&params.github_provider_id)
        .bind(&params.gitlab_provider_id)
        .bind(&params.gitea_provider_id)
        .bind(&params.bitbucket_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: String) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM compose_projects
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
