// Auto-generated by sqlx-gen. Do not edit.

use crate::models::git_providers::GitProvider;

#[derive(Debug, Clone, Default)]
pub struct PaginateGitProviderParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationGitProviderMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedGitProvider {
    pub meta: PaginationGitProviderMeta,
    pub data: Vec<GitProvider>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertGitProviderParams {
    pub name: String,
    pub provider_type: Option<String>,
    pub shared: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteGitProviderParams {
    pub name: String,
    pub provider_type: String,
    pub shared: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateGitProviderParams {
    pub name: Option<String>,
    pub provider_type: Option<String>,
    pub shared: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct GitProviderRepository {
    pool: sqlx::SqlitePool,
}

impl GitProviderRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<GitProvider>, sqlx::Error> {
        sqlx::query_as::<_, GitProvider>(r#"SELECT * FROM git_providers"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateGitProviderParams,
    ) -> Result<PaginatedGitProvider, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM git_providers"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, GitProvider>(
            r#"
            SELECT *
            FROM git_providers
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedGitProvider {
            meta: PaginationGitProviderMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: String) -> Result<Option<GitProvider>, sqlx::Error> {
        sqlx::query_as::<_, GitProvider>(
            r#"
            SELECT *
            FROM git_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertGitProviderParams,
    ) -> Result<GitProvider, sqlx::Error> {
        sqlx::query_as::<
            _,
            GitProvider,
        >(
                r#"
            INSERT INTO git_providers (name, provider_type, shared, created_at, updated_at)
            VALUES (?, COALESCE(?, 'GITHUB'), COALESCE(?, 1), COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.provider_type)
            .bind(&params.shared)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertGitProviderParams>,
    ) -> Result<Vec<GitProvider>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 5usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 5usize;
                let placeholders = vec![
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'GITHUB'"),
                    format!("COALESCE(?, {})", "1"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "git_providers",
                "name, provider_type, shared, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, GitProvider>(&sql);
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.provider_type);
                query = query.bind(&params.shared);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: String,
        params: &OverwriteGitProviderParams,
    ) -> Result<GitProvider, sqlx::Error> {
        sqlx::query_as::<_, GitProvider>(
            r#"
            UPDATE git_providers
            SET
              name = ?,
              provider_type = ?,
              shared = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.provider_type)
        .bind(&params.shared)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: String,
        params: &UpdateGitProviderParams,
    ) -> Result<GitProvider, sqlx::Error> {
        sqlx::query_as::<_, GitProvider>(
            r#"
            UPDATE git_providers
            SET
              name = COALESCE(?, name),
              provider_type = COALESCE(?, provider_type),
              shared = COALESCE(?, shared),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.provider_type)
        .bind(&params.shared)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: String) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM git_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
