// Auto-generated by sqlx-gen. Do not edit.

use crate::models::gitlab_providers::GitlabProvider;

#[derive(Debug, Clone, Default)]
pub struct PaginateGitlabProviderParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationGitlabProviderMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedGitlabProvider {
    pub meta: PaginationGitlabProviderMeta,
    pub data: Vec<GitlabProvider>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertGitlabProviderParams {
    pub gitlab_url: Option<String>,
    pub gitlab_internal_url: Option<String>,
    pub application_id: Option<String>,
    pub redirect_uri: Option<String>,
    pub secret: Option<String>,
    pub access_token: Option<String>,
    pub refresh_token: Option<String>,
    pub group_name: Option<String>,
    pub expires_at: Option<i64>,
    pub git_provider_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteGitlabProviderParams {
    pub gitlab_url: String,
    pub gitlab_internal_url: Option<String>,
    pub application_id: Option<String>,
    pub redirect_uri: Option<String>,
    pub secret: Option<String>,
    pub access_token: Option<String>,
    pub refresh_token: Option<String>,
    pub group_name: Option<String>,
    pub expires_at: Option<i64>,
    pub git_provider_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateGitlabProviderParams {
    pub gitlab_url: Option<String>,
    pub gitlab_internal_url: Option<String>,
    pub application_id: Option<String>,
    pub redirect_uri: Option<String>,
    pub secret: Option<String>,
    pub access_token: Option<String>,
    pub refresh_token: Option<String>,
    pub group_name: Option<String>,
    pub expires_at: Option<i64>,
    pub git_provider_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct GitlabProviderRepository {
    pool: sqlx::SqlitePool,
}

impl GitlabProviderRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<GitlabProvider>, sqlx::Error> {
        sqlx::query_as::<_, GitlabProvider>(r#"SELECT * FROM gitlab_providers"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateGitlabProviderParams,
    ) -> Result<PaginatedGitlabProvider, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM gitlab_providers"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, GitlabProvider>(
            r#"
            SELECT *
            FROM gitlab_providers
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedGitlabProvider {
            meta: PaginationGitlabProviderMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<GitlabProvider>, sqlx::Error> {
        sqlx::query_as::<_, GitlabProvider>(
            r#"
            SELECT *
            FROM gitlab_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertGitlabProviderParams,
    ) -> Result<GitlabProvider, sqlx::Error> {
        sqlx::query_as::<
            _,
            GitlabProvider,
        >(
                r#"
            INSERT INTO gitlab_providers (gitlab_url, gitlab_internal_url, application_id, redirect_uri, secret, access_token, refresh_token, group_name, expires_at, git_provider_id, created_at, updated_at)
            VALUES (COALESCE(?, 'https://gitlab.com'), ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.gitlab_url)
            .bind(&params.gitlab_internal_url)
            .bind(&params.application_id)
            .bind(&params.redirect_uri)
            .bind(&params.secret)
            .bind(&params.access_token)
            .bind(&params.refresh_token)
            .bind(&params.group_name)
            .bind(&params.expires_at)
            .bind(&params.git_provider_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertGitlabProviderParams>,
    ) -> Result<Vec<GitlabProvider>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 12usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 12usize;
                let placeholders = vec![
                    format!("COALESCE(?, {})", "'https://gitlab.com'"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "gitlab_providers",
                "gitlab_url, gitlab_internal_url, application_id, redirect_uri, secret, access_token, refresh_token, group_name, expires_at, git_provider_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, GitlabProvider>(&sql);
            for params in chunk {
                query = query.bind(&params.gitlab_url);
                query = query.bind(&params.gitlab_internal_url);
                query = query.bind(&params.application_id);
                query = query.bind(&params.redirect_uri);
                query = query.bind(&params.secret);
                query = query.bind(&params.access_token);
                query = query.bind(&params.refresh_token);
                query = query.bind(&params.group_name);
                query = query.bind(&params.expires_at);
                query = query.bind(&params.git_provider_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteGitlabProviderParams,
    ) -> Result<GitlabProvider, sqlx::Error> {
        sqlx::query_as::<_, GitlabProvider>(
            r#"
            UPDATE gitlab_providers
            SET
              gitlab_url = ?,
              gitlab_internal_url = ?,
              application_id = ?,
              redirect_uri = ?,
              secret = ?,
              access_token = ?,
              refresh_token = ?,
              group_name = ?,
              expires_at = ?,
              git_provider_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.gitlab_url)
        .bind(&params.gitlab_internal_url)
        .bind(&params.application_id)
        .bind(&params.redirect_uri)
        .bind(&params.secret)
        .bind(&params.access_token)
        .bind(&params.refresh_token)
        .bind(&params.group_name)
        .bind(&params.expires_at)
        .bind(&params.git_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateGitlabProviderParams,
    ) -> Result<GitlabProvider, sqlx::Error> {
        sqlx::query_as::<_, GitlabProvider>(
            r#"
            UPDATE gitlab_providers
            SET
              gitlab_url = COALESCE(?, gitlab_url),
              gitlab_internal_url = COALESCE(?, gitlab_internal_url),
              application_id = COALESCE(?, application_id),
              redirect_uri = COALESCE(?, redirect_uri),
              secret = COALESCE(?, secret),
              access_token = COALESCE(?, access_token),
              refresh_token = COALESCE(?, refresh_token),
              group_name = COALESCE(?, group_name),
              expires_at = COALESCE(?, expires_at),
              git_provider_id = COALESCE(?, git_provider_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.gitlab_url)
        .bind(&params.gitlab_internal_url)
        .bind(&params.application_id)
        .bind(&params.redirect_uri)
        .bind(&params.secret)
        .bind(&params.access_token)
        .bind(&params.refresh_token)
        .bind(&params.group_name)
        .bind(&params.expires_at)
        .bind(&params.git_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM gitlab_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
