// Auto-generated by sqlx-gen. Do not edit.

use crate::models::jwt_tokens::JwtToken;

#[derive(Debug, Clone, Default)]
pub struct PaginateJwtTokenParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationJwtTokenMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedJwtToken {
    pub meta: PaginationJwtTokenMeta,
    pub data: Vec<JwtToken>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertJwtTokenParams {
    pub jti: String,
    pub role: String,
    pub user_id: i64,
    pub is_blacklist: Option<i64>,
    pub blacklist_at: Option<i64>,
    pub expired_at: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteJwtTokenParams {
    pub jti: String,
    pub role: String,
    pub user_id: i64,
    pub is_blacklist: Option<i64>,
    pub blacklist_at: Option<i64>,
    pub expired_at: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateJwtTokenParams {
    pub jti: Option<String>,
    pub role: Option<String>,
    pub user_id: Option<i64>,
    pub is_blacklist: Option<i64>,
    pub blacklist_at: Option<i64>,
    pub expired_at: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct JwtTokenRepository {
    pool: sqlx::SqlitePool,
}

impl JwtTokenRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<JwtToken>, sqlx::Error> {
        sqlx::query_as::<_, JwtToken>(r#"SELECT * FROM jwt_tokens"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateJwtTokenParams,
    ) -> Result<PaginatedJwtToken, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM jwt_tokens"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, JwtToken>(
            r#"
            SELECT *
            FROM jwt_tokens
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedJwtToken {
            meta: PaginationJwtTokenMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<JwtToken>, sqlx::Error> {
        sqlx::query_as::<_, JwtToken>(
            r#"
            SELECT *
            FROM jwt_tokens
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertJwtTokenParams) -> Result<JwtToken, sqlx::Error> {
        sqlx::query_as::<
            _,
            JwtToken,
        >(
                r#"
            INSERT INTO jwt_tokens (jti, role, user_id, is_blacklist, blacklist_at, expired_at, created_at, updated_at)
            VALUES (?, ?, ?, COALESCE(?, 0), ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.jti)
            .bind(&params.role)
            .bind(&params.user_id)
            .bind(&params.is_blacklist)
            .bind(&params.blacklist_at)
            .bind(&params.expired_at)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertJwtTokenParams>,
    ) -> Result<Vec<JwtToken>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 8usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 8usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "0"),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "jwt_tokens",
                "jti, role, user_id, is_blacklist, blacklist_at, expired_at, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, JwtToken>(&sql);
            for params in chunk {
                query = query.bind(&params.jti);
                query = query.bind(&params.role);
                query = query.bind(&params.user_id);
                query = query.bind(&params.is_blacklist);
                query = query.bind(&params.blacklist_at);
                query = query.bind(&params.expired_at);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteJwtTokenParams,
    ) -> Result<JwtToken, sqlx::Error> {
        sqlx::query_as::<_, JwtToken>(
            r#"
            UPDATE jwt_tokens
            SET
              jti = ?,
              role = ?,
              user_id = ?,
              is_blacklist = ?,
              blacklist_at = ?,
              expired_at = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.jti)
        .bind(&params.role)
        .bind(&params.user_id)
        .bind(&params.is_blacklist)
        .bind(&params.blacklist_at)
        .bind(&params.expired_at)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateJwtTokenParams,
    ) -> Result<JwtToken, sqlx::Error> {
        sqlx::query_as::<_, JwtToken>(
            r#"
            UPDATE jwt_tokens
            SET
              jti = COALESCE(?, jti),
              role = COALESCE(?, role),
              user_id = COALESCE(?, user_id),
              is_blacklist = COALESCE(?, is_blacklist),
              blacklist_at = COALESCE(?, blacklist_at),
              expired_at = COALESCE(?, expired_at),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.jti)
        .bind(&params.role)
        .bind(&params.user_id)
        .bind(&params.is_blacklist)
        .bind(&params.blacklist_at)
        .bind(&params.expired_at)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM jwt_tokens
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
