// Auto-generated by sqlx-gen. Do not edit.

use crate::models::notif_teams::NotifTeam;

#[derive(Debug, Clone, Default)]
pub struct PaginateNotifTeamParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationNotifTeamMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedNotifTeam {
    pub meta: PaginationNotifTeamMeta,
    pub data: Vec<NotifTeam>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertNotifTeamParams {
    pub webhook_url: String,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteNotifTeamParams {
    pub webhook_url: String,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateNotifTeamParams {
    pub webhook_url: Option<String>,
}

pub struct NotifTeamRepository {
    pool: sqlx::SqlitePool,
}

impl NotifTeamRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<NotifTeam>, sqlx::Error> {
        sqlx::query_as::<_, NotifTeam>(r#"SELECT * FROM notif_teams"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateNotifTeamParams,
    ) -> Result<PaginatedNotifTeam, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM notif_teams"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, NotifTeam>(
            r#"
            SELECT *
            FROM notif_teams
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedNotifTeam {
            meta: PaginationNotifTeamMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<NotifTeam>, sqlx::Error> {
        sqlx::query_as::<_, NotifTeam>(
            r#"
            SELECT *
            FROM notif_teams
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertNotifTeamParams) -> Result<NotifTeam, sqlx::Error> {
        sqlx::query_as::<_, NotifTeam>(
            r#"
            INSERT INTO notif_teams (webhook_url)
            VALUES (?)
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertNotifTeamParams>,
    ) -> Result<Vec<NotifTeam>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 1usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 1usize;
                let placeholders = vec!["?".to_string()];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "notif_teams",
                "webhook_url",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, NotifTeam>(&sql);
            for params in chunk {
                query = query.bind(&params.webhook_url);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteNotifTeamParams,
    ) -> Result<NotifTeam, sqlx::Error> {
        sqlx::query_as::<_, NotifTeam>(
            r#"
            UPDATE notif_teams
            SET
              webhook_url = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateNotifTeamParams,
    ) -> Result<NotifTeam, sqlx::Error> {
        sqlx::query_as::<_, NotifTeam>(
            r#"
            UPDATE notif_teams
            SET
              webhook_url = COALESCE(?, webhook_url)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM notif_teams
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
