// Auto-generated by sqlx-gen. Do not edit.

use crate::models::notifications::Notification;

#[derive(Debug, Clone, Default)]
pub struct PaginateNotificationParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationNotificationMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedNotification {
    pub meta: PaginationNotificationMeta,
    pub data: Vec<Notification>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertNotificationParams {
    pub name: String,
    pub notification_type: String,
    pub on_app_deploy: Option<i64>,
    pub on_app_build_error: Option<i64>,
    pub on_database_backup: Option<i64>,
    pub on_volume_backup: Option<i64>,
    pub on_panel_restart: Option<i64>,
    pub on_docker_cleanup: Option<i64>,
    pub on_server_threshold: Option<i64>,
    pub slack_id: Option<i64>,
    pub telegram_id: Option<i64>,
    pub discord_id: Option<i64>,
    pub email_id: Option<i64>,
    pub resend_id: Option<i64>,
    pub gotify_id: Option<i64>,
    pub ntfy_id: Option<i64>,
    pub mattermost_id: Option<i64>,
    pub custom_id: Option<i64>,
    pub lark_id: Option<i64>,
    pub pushover_id: Option<i64>,
    pub teams_id: Option<i64>,
    pub organization_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteNotificationParams {
    pub name: String,
    pub notification_type: String,
    pub on_app_deploy: i64,
    pub on_app_build_error: i64,
    pub on_database_backup: i64,
    pub on_volume_backup: i64,
    pub on_panel_restart: i64,
    pub on_docker_cleanup: i64,
    pub on_server_threshold: i64,
    pub slack_id: Option<i64>,
    pub telegram_id: Option<i64>,
    pub discord_id: Option<i64>,
    pub email_id: Option<i64>,
    pub resend_id: Option<i64>,
    pub gotify_id: Option<i64>,
    pub ntfy_id: Option<i64>,
    pub mattermost_id: Option<i64>,
    pub custom_id: Option<i64>,
    pub lark_id: Option<i64>,
    pub pushover_id: Option<i64>,
    pub teams_id: Option<i64>,
    pub organization_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateNotificationParams {
    pub name: Option<String>,
    pub notification_type: Option<String>,
    pub on_app_deploy: Option<i64>,
    pub on_app_build_error: Option<i64>,
    pub on_database_backup: Option<i64>,
    pub on_volume_backup: Option<i64>,
    pub on_panel_restart: Option<i64>,
    pub on_docker_cleanup: Option<i64>,
    pub on_server_threshold: Option<i64>,
    pub slack_id: Option<i64>,
    pub telegram_id: Option<i64>,
    pub discord_id: Option<i64>,
    pub email_id: Option<i64>,
    pub resend_id: Option<i64>,
    pub gotify_id: Option<i64>,
    pub ntfy_id: Option<i64>,
    pub mattermost_id: Option<i64>,
    pub custom_id: Option<i64>,
    pub lark_id: Option<i64>,
    pub pushover_id: Option<i64>,
    pub teams_id: Option<i64>,
    pub organization_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct NotificationRepository {
    pool: sqlx::SqlitePool,
}

impl NotificationRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Notification>, sqlx::Error> {
        sqlx::query_as::<_, Notification>(r#"SELECT * FROM notifications"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateNotificationParams,
    ) -> Result<PaginatedNotification, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM notifications"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Notification>(
            r#"
            SELECT *
            FROM notifications
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedNotification {
            meta: PaginationNotificationMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Notification>, sqlx::Error> {
        sqlx::query_as::<_, Notification>(
            r#"
            SELECT *
            FROM notifications
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertNotificationParams,
    ) -> Result<Notification, sqlx::Error> {
        sqlx::query_as::<
            _,
            Notification,
        >(
                r#"
            INSERT INTO notifications (name, notification_type, on_app_deploy, on_app_build_error, on_database_backup, on_volume_backup, on_panel_restart, on_docker_cleanup, on_server_threshold, slack_id, telegram_id, discord_id, email_id, resend_id, gotify_id, ntfy_id, mattermost_id, custom_id, lark_id, pushover_id, teams_id, organization_id, created_at, updated_at)
            VALUES (?, ?, COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, 0), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.notification_type)
            .bind(&params.on_app_deploy)
            .bind(&params.on_app_build_error)
            .bind(&params.on_database_backup)
            .bind(&params.on_volume_backup)
            .bind(&params.on_panel_restart)
            .bind(&params.on_docker_cleanup)
            .bind(&params.on_server_threshold)
            .bind(&params.slack_id)
            .bind(&params.telegram_id)
            .bind(&params.discord_id)
            .bind(&params.email_id)
            .bind(&params.resend_id)
            .bind(&params.gotify_id)
            .bind(&params.ntfy_id)
            .bind(&params.mattermost_id)
            .bind(&params.custom_id)
            .bind(&params.lark_id)
            .bind(&params.pushover_id)
            .bind(&params.teams_id)
            .bind(&params.organization_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertNotificationParams>,
    ) -> Result<Vec<Notification>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 24usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 24usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "notifications",
                "name, notification_type, on_app_deploy, on_app_build_error, on_database_backup, on_volume_backup, on_panel_restart, on_docker_cleanup, on_server_threshold, slack_id, telegram_id, discord_id, email_id, resend_id, gotify_id, ntfy_id, mattermost_id, custom_id, lark_id, pushover_id, teams_id, organization_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Notification>(&sql);
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.notification_type);
                query = query.bind(&params.on_app_deploy);
                query = query.bind(&params.on_app_build_error);
                query = query.bind(&params.on_database_backup);
                query = query.bind(&params.on_volume_backup);
                query = query.bind(&params.on_panel_restart);
                query = query.bind(&params.on_docker_cleanup);
                query = query.bind(&params.on_server_threshold);
                query = query.bind(&params.slack_id);
                query = query.bind(&params.telegram_id);
                query = query.bind(&params.discord_id);
                query = query.bind(&params.email_id);
                query = query.bind(&params.resend_id);
                query = query.bind(&params.gotify_id);
                query = query.bind(&params.ntfy_id);
                query = query.bind(&params.mattermost_id);
                query = query.bind(&params.custom_id);
                query = query.bind(&params.lark_id);
                query = query.bind(&params.pushover_id);
                query = query.bind(&params.teams_id);
                query = query.bind(&params.organization_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteNotificationParams,
    ) -> Result<Notification, sqlx::Error> {
        sqlx::query_as::<_, Notification>(
            r#"
            UPDATE notifications
            SET
              name = ?,
              notification_type = ?,
              on_app_deploy = ?,
              on_app_build_error = ?,
              on_database_backup = ?,
              on_volume_backup = ?,
              on_panel_restart = ?,
              on_docker_cleanup = ?,
              on_server_threshold = ?,
              slack_id = ?,
              telegram_id = ?,
              discord_id = ?,
              email_id = ?,
              resend_id = ?,
              gotify_id = ?,
              ntfy_id = ?,
              mattermost_id = ?,
              custom_id = ?,
              lark_id = ?,
              pushover_id = ?,
              teams_id = ?,
              organization_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.notification_type)
        .bind(&params.on_app_deploy)
        .bind(&params.on_app_build_error)
        .bind(&params.on_database_backup)
        .bind(&params.on_volume_backup)
        .bind(&params.on_panel_restart)
        .bind(&params.on_docker_cleanup)
        .bind(&params.on_server_threshold)
        .bind(&params.slack_id)
        .bind(&params.telegram_id)
        .bind(&params.discord_id)
        .bind(&params.email_id)
        .bind(&params.resend_id)
        .bind(&params.gotify_id)
        .bind(&params.ntfy_id)
        .bind(&params.mattermost_id)
        .bind(&params.custom_id)
        .bind(&params.lark_id)
        .bind(&params.pushover_id)
        .bind(&params.teams_id)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateNotificationParams,
    ) -> Result<Notification, sqlx::Error> {
        sqlx::query_as::<_, Notification>(
            r#"
            UPDATE notifications
            SET
              name = COALESCE(?, name),
              notification_type = COALESCE(?, notification_type),
              on_app_deploy = COALESCE(?, on_app_deploy),
              on_app_build_error = COALESCE(?, on_app_build_error),
              on_database_backup = COALESCE(?, on_database_backup),
              on_volume_backup = COALESCE(?, on_volume_backup),
              on_panel_restart = COALESCE(?, on_panel_restart),
              on_docker_cleanup = COALESCE(?, on_docker_cleanup),
              on_server_threshold = COALESCE(?, on_server_threshold),
              slack_id = COALESCE(?, slack_id),
              telegram_id = COALESCE(?, telegram_id),
              discord_id = COALESCE(?, discord_id),
              email_id = COALESCE(?, email_id),
              resend_id = COALESCE(?, resend_id),
              gotify_id = COALESCE(?, gotify_id),
              ntfy_id = COALESCE(?, ntfy_id),
              mattermost_id = COALESCE(?, mattermost_id),
              custom_id = COALESCE(?, custom_id),
              lark_id = COALESCE(?, lark_id),
              pushover_id = COALESCE(?, pushover_id),
              teams_id = COALESCE(?, teams_id),
              organization_id = COALESCE(?, organization_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.notification_type)
        .bind(&params.on_app_deploy)
        .bind(&params.on_app_build_error)
        .bind(&params.on_database_backup)
        .bind(&params.on_volume_backup)
        .bind(&params.on_panel_restart)
        .bind(&params.on_docker_cleanup)
        .bind(&params.on_server_threshold)
        .bind(&params.slack_id)
        .bind(&params.telegram_id)
        .bind(&params.discord_id)
        .bind(&params.email_id)
        .bind(&params.resend_id)
        .bind(&params.gotify_id)
        .bind(&params.ntfy_id)
        .bind(&params.mattermost_id)
        .bind(&params.custom_id)
        .bind(&params.lark_id)
        .bind(&params.pushover_id)
        .bind(&params.teams_id)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM notifications
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
