// Auto-generated by sqlx-gen. Do not edit.

use crate::models::notif_custom::NotifCustom;

#[derive(Debug, Clone, Default)]
pub struct PaginateNotifCustomParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationNotifCustomMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedNotifCustom {
    pub meta: PaginationNotifCustomMeta,
    pub data: Vec<NotifCustom>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertNotifCustomParams {
    pub endpoint: String,
    pub headers: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteNotifCustomParams {
    pub endpoint: String,
    pub headers: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateNotifCustomParams {
    pub endpoint: Option<String>,
    pub headers: Option<String>,
}

pub struct NotifCustomRepository {
    pool: sqlx::SqlitePool,
}

impl NotifCustomRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<NotifCustom>, sqlx::Error> {
        sqlx::query_as::<_, NotifCustom>(r#"SELECT * FROM notif_custom"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateNotifCustomParams,
    ) -> Result<PaginatedNotifCustom, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM notif_custom"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, NotifCustom>(
            r#"
            SELECT *
            FROM notif_custom
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedNotifCustom {
            meta: PaginationNotifCustomMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<NotifCustom>, sqlx::Error> {
        sqlx::query_as::<_, NotifCustom>(
            r#"
            SELECT *
            FROM notif_custom
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertNotifCustomParams,
    ) -> Result<NotifCustom, sqlx::Error> {
        sqlx::query_as::<_, NotifCustom>(
            r#"
            INSERT INTO notif_custom (endpoint, headers)
            VALUES (?, ?)
            RETURNING *
        "#,
        )
        .bind(&params.endpoint)
        .bind(&params.headers)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertNotifCustomParams>,
    ) -> Result<Vec<NotifCustom>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 2usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 2usize;
                let placeholders = vec!["?".to_string(), "?".to_string()];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "notif_custom",
                "endpoint, headers",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, NotifCustom>(&sql);
            for params in chunk {
                query = query.bind(&params.endpoint);
                query = query.bind(&params.headers);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteNotifCustomParams,
    ) -> Result<NotifCustom, sqlx::Error> {
        sqlx::query_as::<_, NotifCustom>(
            r#"
            UPDATE notif_custom
            SET
              endpoint = ?,
              headers = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.endpoint)
        .bind(&params.headers)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateNotifCustomParams,
    ) -> Result<NotifCustom, sqlx::Error> {
        sqlx::query_as::<_, NotifCustom>(
            r#"
            UPDATE notif_custom
            SET
              endpoint = COALESCE(?, endpoint),
              headers = COALESCE(?, headers)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.endpoint)
        .bind(&params.headers)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM notif_custom
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
