// Auto-generated by sqlx-gen. Do not edit.

use crate::models::notif_gotify::NotifGotify;

#[derive(Debug, Clone, Default)]
pub struct PaginateNotifGotifyParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationNotifGotifyMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedNotifGotify {
    pub meta: PaginationNotifGotifyMeta,
    pub data: Vec<NotifGotify>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertNotifGotifyParams {
    pub server_url: String,
    pub app_token: String,
    pub priority: Option<i64>,
    pub decoration: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteNotifGotifyParams {
    pub server_url: String,
    pub app_token: String,
    pub priority: i64,
    pub decoration: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateNotifGotifyParams {
    pub server_url: Option<String>,
    pub app_token: Option<String>,
    pub priority: Option<i64>,
    pub decoration: Option<i64>,
}

pub struct NotifGotifyRepository {
    pool: sqlx::SqlitePool,
}

impl NotifGotifyRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<NotifGotify>, sqlx::Error> {
        sqlx::query_as::<_, NotifGotify>(r#"SELECT * FROM notif_gotify"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateNotifGotifyParams,
    ) -> Result<PaginatedNotifGotify, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM notif_gotify"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, NotifGotify>(
            r#"
            SELECT *
            FROM notif_gotify
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedNotifGotify {
            meta: PaginationNotifGotifyMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<NotifGotify>, sqlx::Error> {
        sqlx::query_as::<_, NotifGotify>(
            r#"
            SELECT *
            FROM notif_gotify
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertNotifGotifyParams,
    ) -> Result<NotifGotify, sqlx::Error> {
        sqlx::query_as::<_, NotifGotify>(
            r#"
            INSERT INTO notif_gotify (server_url, app_token, priority, decoration)
            VALUES (?, ?, COALESCE(?, 5), COALESCE(?, 0))
            RETURNING *
        "#,
        )
        .bind(&params.server_url)
        .bind(&params.app_token)
        .bind(&params.priority)
        .bind(&params.decoration)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertNotifGotifyParams>,
    ) -> Result<Vec<NotifGotify>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 4usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 4usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "5"),
                    format!("COALESCE(?, {})", "0"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "notif_gotify",
                "server_url, app_token, priority, decoration",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, NotifGotify>(&sql);
            for params in chunk {
                query = query.bind(&params.server_url);
                query = query.bind(&params.app_token);
                query = query.bind(&params.priority);
                query = query.bind(&params.decoration);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteNotifGotifyParams,
    ) -> Result<NotifGotify, sqlx::Error> {
        sqlx::query_as::<_, NotifGotify>(
            r#"
            UPDATE notif_gotify
            SET
              server_url = ?,
              app_token = ?,
              priority = ?,
              decoration = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.server_url)
        .bind(&params.app_token)
        .bind(&params.priority)
        .bind(&params.decoration)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateNotifGotifyParams,
    ) -> Result<NotifGotify, sqlx::Error> {
        sqlx::query_as::<_, NotifGotify>(
            r#"
            UPDATE notif_gotify
            SET
              server_url = COALESCE(?, server_url),
              app_token = COALESCE(?, app_token),
              priority = COALESCE(?, priority),
              decoration = COALESCE(?, decoration)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.server_url)
        .bind(&params.app_token)
        .bind(&params.priority)
        .bind(&params.decoration)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM notif_gotify
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
