// Auto-generated by sqlx-gen. Do not edit.

use crate::models::notif_ntfy::NotifNtfy;

#[derive(Debug, Clone, Default)]
pub struct PaginateNotifNtfyParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationNotifNtfyMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedNotifNtfy {
    pub meta: PaginationNotifNtfyMeta,
    pub data: Vec<NotifNtfy>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertNotifNtfyParams {
    pub server_url: String,
    pub topic: String,
    pub access_token: Option<String>,
    pub priority: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteNotifNtfyParams {
    pub server_url: String,
    pub topic: String,
    pub access_token: Option<String>,
    pub priority: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateNotifNtfyParams {
    pub server_url: Option<String>,
    pub topic: Option<String>,
    pub access_token: Option<String>,
    pub priority: Option<i64>,
}

pub struct NotifNtfyRepository {
    pool: sqlx::SqlitePool,
}

impl NotifNtfyRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<NotifNtfy>, sqlx::Error> {
        sqlx::query_as::<_, NotifNtfy>(r#"SELECT * FROM notif_ntfy"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateNotifNtfyParams,
    ) -> Result<PaginatedNotifNtfy, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM notif_ntfy"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, NotifNtfy>(
            r#"
            SELECT *
            FROM notif_ntfy
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedNotifNtfy {
            meta: PaginationNotifNtfyMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<NotifNtfy>, sqlx::Error> {
        sqlx::query_as::<_, NotifNtfy>(
            r#"
            SELECT *
            FROM notif_ntfy
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertNotifNtfyParams) -> Result<NotifNtfy, sqlx::Error> {
        sqlx::query_as::<_, NotifNtfy>(
            r#"
            INSERT INTO notif_ntfy (server_url, topic, access_token, priority)
            VALUES (?, ?, ?, COALESCE(?, 3))
            RETURNING *
        "#,
        )
        .bind(&params.server_url)
        .bind(&params.topic)
        .bind(&params.access_token)
        .bind(&params.priority)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertNotifNtfyParams>,
    ) -> Result<Vec<NotifNtfy>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 4usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 4usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "3"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "notif_ntfy",
                "server_url, topic, access_token, priority",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, NotifNtfy>(&sql);
            for params in chunk {
                query = query.bind(&params.server_url);
                query = query.bind(&params.topic);
                query = query.bind(&params.access_token);
                query = query.bind(&params.priority);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteNotifNtfyParams,
    ) -> Result<NotifNtfy, sqlx::Error> {
        sqlx::query_as::<_, NotifNtfy>(
            r#"
            UPDATE notif_ntfy
            SET
              server_url = ?,
              topic = ?,
              access_token = ?,
              priority = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.server_url)
        .bind(&params.topic)
        .bind(&params.access_token)
        .bind(&params.priority)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateNotifNtfyParams,
    ) -> Result<NotifNtfy, sqlx::Error> {
        sqlx::query_as::<_, NotifNtfy>(
            r#"
            UPDATE notif_ntfy
            SET
              server_url = COALESCE(?, server_url),
              topic = COALESCE(?, topic),
              access_token = COALESCE(?, access_token),
              priority = COALESCE(?, priority)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.server_url)
        .bind(&params.topic)
        .bind(&params.access_token)
        .bind(&params.priority)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM notif_ntfy
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
