// Auto-generated by sqlx-gen. Do not edit.

use crate::models::notif_mattermost::NotifMattermost;

#[derive(Debug, Clone, Default)]
pub struct PaginateNotifMattermostParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationNotifMattermostMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedNotifMattermost {
    pub meta: PaginationNotifMattermostMeta,
    pub data: Vec<NotifMattermost>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertNotifMattermostParams {
    pub webhook_url: String,
    pub channel: Option<String>,
    pub username: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteNotifMattermostParams {
    pub webhook_url: String,
    pub channel: Option<String>,
    pub username: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateNotifMattermostParams {
    pub webhook_url: Option<String>,
    pub channel: Option<String>,
    pub username: Option<String>,
}

pub struct NotifMattermostRepository {
    pool: sqlx::SqlitePool,
}

impl NotifMattermostRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<NotifMattermost>, sqlx::Error> {
        sqlx::query_as::<_, NotifMattermost>(r#"SELECT * FROM notif_mattermost"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateNotifMattermostParams,
    ) -> Result<PaginatedNotifMattermost, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM notif_mattermost"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, NotifMattermost>(
            r#"
            SELECT *
            FROM notif_mattermost
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedNotifMattermost {
            meta: PaginationNotifMattermostMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<NotifMattermost>, sqlx::Error> {
        sqlx::query_as::<_, NotifMattermost>(
            r#"
            SELECT *
            FROM notif_mattermost
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertNotifMattermostParams,
    ) -> Result<NotifMattermost, sqlx::Error> {
        sqlx::query_as::<_, NotifMattermost>(
            r#"
            INSERT INTO notif_mattermost (webhook_url, channel, username)
            VALUES (?, ?, ?)
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .bind(&params.channel)
        .bind(&params.username)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertNotifMattermostParams>,
    ) -> Result<Vec<NotifMattermost>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 3usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 3usize;
                let placeholders = vec!["?".to_string(), "?".to_string(), "?".to_string()];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "notif_mattermost",
                "webhook_url, channel, username",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, NotifMattermost>(&sql);
            for params in chunk {
                query = query.bind(&params.webhook_url);
                query = query.bind(&params.channel);
                query = query.bind(&params.username);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteNotifMattermostParams,
    ) -> Result<NotifMattermost, sqlx::Error> {
        sqlx::query_as::<_, NotifMattermost>(
            r#"
            UPDATE notif_mattermost
            SET
              webhook_url = ?,
              channel = ?,
              username = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .bind(&params.channel)
        .bind(&params.username)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateNotifMattermostParams,
    ) -> Result<NotifMattermost, sqlx::Error> {
        sqlx::query_as::<_, NotifMattermost>(
            r#"
            UPDATE notif_mattermost
            SET
              webhook_url = COALESCE(?, webhook_url),
              channel = COALESCE(?, channel),
              username = COALESCE(?, username)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .bind(&params.channel)
        .bind(&params.username)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM notif_mattermost
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
