// Auto-generated by sqlx-gen. Do not edit.

use crate::models::registries::Registry;

#[derive(Debug, Clone, Default)]
pub struct PaginateRegistryParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationRegistryMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedRegistry {
    pub meta: PaginationRegistryMeta,
    pub data: Vec<Registry>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertRegistryParams {
    pub registry_name: String,
    pub image_prefix: Option<String>,
    pub username: String,
    pub password: String,
    pub registry_url: Option<String>,
    pub registry_type: Option<String>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteRegistryParams {
    pub registry_name: String,
    pub image_prefix: Option<String>,
    pub username: String,
    pub password: String,
    pub registry_url: String,
    pub registry_type: String,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateRegistryParams {
    pub registry_name: Option<String>,
    pub image_prefix: Option<String>,
    pub username: Option<String>,
    pub password: Option<String>,
    pub registry_url: Option<String>,
    pub registry_type: Option<String>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct RegistryRepository {
    pool: sqlx::SqlitePool,
}

impl RegistryRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Registry>, sqlx::Error> {
        sqlx::query_as::<_, Registry>(r#"SELECT * FROM registries"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateRegistryParams,
    ) -> Result<PaginatedRegistry, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM registries"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Registry>(
            r#"
            SELECT *
            FROM registries
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedRegistry {
            meta: PaginationRegistryMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Registry>, sqlx::Error> {
        sqlx::query_as::<_, Registry>(
            r#"
            SELECT *
            FROM registries
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertRegistryParams) -> Result<Registry, sqlx::Error> {
        sqlx::query_as::<
            _,
            Registry,
        >(
                r#"
            INSERT INTO registries (registry_name, image_prefix, username, password, registry_url, registry_type, created_at, updated_at)
            VALUES (?, ?, ?, ?, COALESCE(?, ''), COALESCE(?, 'CLOUD'), COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.registry_name)
            .bind(&params.image_prefix)
            .bind(&params.username)
            .bind(&params.password)
            .bind(&params.registry_url)
            .bind(&params.registry_type)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertRegistryParams>,
    ) -> Result<Vec<Registry>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 8usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 8usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "''"),
                    format!("COALESCE(?, {})", "'CLOUD'"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "registries",
                "registry_name, image_prefix, username, password, registry_url, registry_type, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Registry>(&sql);
            for params in chunk {
                query = query.bind(&params.registry_name);
                query = query.bind(&params.image_prefix);
                query = query.bind(&params.username);
                query = query.bind(&params.password);
                query = query.bind(&params.registry_url);
                query = query.bind(&params.registry_type);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteRegistryParams,
    ) -> Result<Registry, sqlx::Error> {
        sqlx::query_as::<_, Registry>(
            r#"
            UPDATE registries
            SET
              registry_name = ?,
              image_prefix = ?,
              username = ?,
              password = ?,
              registry_url = ?,
              registry_type = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.registry_name)
        .bind(&params.image_prefix)
        .bind(&params.username)
        .bind(&params.password)
        .bind(&params.registry_url)
        .bind(&params.registry_type)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateRegistryParams,
    ) -> Result<Registry, sqlx::Error> {
        sqlx::query_as::<_, Registry>(
            r#"
            UPDATE registries
            SET
              registry_name = COALESCE(?, registry_name),
              image_prefix = COALESCE(?, image_prefix),
              username = COALESCE(?, username),
              password = COALESCE(?, password),
              registry_url = COALESCE(?, registry_url),
              registry_type = COALESCE(?, registry_type),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.registry_name)
        .bind(&params.image_prefix)
        .bind(&params.username)
        .bind(&params.password)
        .bind(&params.registry_url)
        .bind(&params.registry_type)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM registries
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
