// Auto-generated by sqlx-gen. Do not edit.

use crate::models::schedules::Schedule;

#[derive(Debug, Clone, Default)]
pub struct PaginateScheduleParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationScheduleMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedSchedule {
    pub meta: PaginationScheduleMeta,
    pub data: Vec<Schedule>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertScheduleParams {
    pub name: String,
    pub description: Option<String>,
    pub cron_expression: String,
    pub app_name: String,
    pub service_name: Option<String>,
    pub shell_type: Option<String>,
    pub schedule_type: Option<String>,
    pub command: String,
    pub script: Option<String>,
    pub timezone: Option<String>,
    pub enabled: Option<i64>,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub server_id: Option<i64>,
    pub organization_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteScheduleParams {
    pub name: String,
    pub description: Option<String>,
    pub cron_expression: String,
    pub app_name: String,
    pub service_name: Option<String>,
    pub shell_type: String,
    pub schedule_type: String,
    pub command: String,
    pub script: Option<String>,
    pub timezone: Option<String>,
    pub enabled: i64,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub server_id: Option<i64>,
    pub organization_id: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateScheduleParams {
    pub name: Option<String>,
    pub description: Option<String>,
    pub cron_expression: Option<String>,
    pub app_name: Option<String>,
    pub service_name: Option<String>,
    pub shell_type: Option<String>,
    pub schedule_type: Option<String>,
    pub command: Option<String>,
    pub script: Option<String>,
    pub timezone: Option<String>,
    pub enabled: Option<i64>,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub server_id: Option<i64>,
    pub organization_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct ScheduleRepository {
    pool: sqlx::SqlitePool,
}

impl ScheduleRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Schedule>, sqlx::Error> {
        sqlx::query_as::<_, Schedule>(r#"SELECT * FROM schedules"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateScheduleParams,
    ) -> Result<PaginatedSchedule, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM schedules"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Schedule>(
            r#"
            SELECT *
            FROM schedules
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedSchedule {
            meta: PaginationScheduleMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Schedule>, sqlx::Error> {
        sqlx::query_as::<_, Schedule>(
            r#"
            SELECT *
            FROM schedules
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertScheduleParams) -> Result<Schedule, sqlx::Error> {
        sqlx::query_as::<
            _,
            Schedule,
        >(
                r#"
            INSERT INTO schedules (name, description, cron_expression, app_name, service_name, shell_type, schedule_type, command, script, timezone, enabled, application_id, compose_id, server_id, organization_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, COALESCE(?, 'BASH'), COALESCE(?, 'APPLICATION'), ?, ?, ?, COALESCE(?, 1), ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.description)
            .bind(&params.cron_expression)
            .bind(&params.app_name)
            .bind(&params.service_name)
            .bind(&params.shell_type)
            .bind(&params.schedule_type)
            .bind(&params.command)
            .bind(&params.script)
            .bind(&params.timezone)
            .bind(&params.enabled)
            .bind(&params.application_id)
            .bind(&params.compose_id)
            .bind(&params.server_id)
            .bind(&params.organization_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertScheduleParams>,
    ) -> Result<Vec<Schedule>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 17usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 17usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'BASH'"),
                    format!("COALESCE(?, {})", "'APPLICATION'"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "1"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "schedules",
                "name, description, cron_expression, app_name, service_name, shell_type, schedule_type, command, script, timezone, enabled, application_id, compose_id, server_id, organization_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Schedule>(&sql);
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.description);
                query = query.bind(&params.cron_expression);
                query = query.bind(&params.app_name);
                query = query.bind(&params.service_name);
                query = query.bind(&params.shell_type);
                query = query.bind(&params.schedule_type);
                query = query.bind(&params.command);
                query = query.bind(&params.script);
                query = query.bind(&params.timezone);
                query = query.bind(&params.enabled);
                query = query.bind(&params.application_id);
                query = query.bind(&params.compose_id);
                query = query.bind(&params.server_id);
                query = query.bind(&params.organization_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteScheduleParams,
    ) -> Result<Schedule, sqlx::Error> {
        sqlx::query_as::<_, Schedule>(
            r#"
            UPDATE schedules
            SET
              name = ?,
              description = ?,
              cron_expression = ?,
              app_name = ?,
              service_name = ?,
              shell_type = ?,
              schedule_type = ?,
              command = ?,
              script = ?,
              timezone = ?,
              enabled = ?,
              application_id = ?,
              compose_id = ?,
              server_id = ?,
              organization_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.cron_expression)
        .bind(&params.app_name)
        .bind(&params.service_name)
        .bind(&params.shell_type)
        .bind(&params.schedule_type)
        .bind(&params.command)
        .bind(&params.script)
        .bind(&params.timezone)
        .bind(&params.enabled)
        .bind(&params.application_id)
        .bind(&params.compose_id)
        .bind(&params.server_id)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateScheduleParams,
    ) -> Result<Schedule, sqlx::Error> {
        sqlx::query_as::<_, Schedule>(
            r#"
            UPDATE schedules
            SET
              name = COALESCE(?, name),
              description = COALESCE(?, description),
              cron_expression = COALESCE(?, cron_expression),
              app_name = COALESCE(?, app_name),
              service_name = COALESCE(?, service_name),
              shell_type = COALESCE(?, shell_type),
              schedule_type = COALESCE(?, schedule_type),
              command = COALESCE(?, command),
              script = COALESCE(?, script),
              timezone = COALESCE(?, timezone),
              enabled = COALESCE(?, enabled),
              application_id = COALESCE(?, application_id),
              compose_id = COALESCE(?, compose_id),
              server_id = COALESCE(?, server_id),
              organization_id = COALESCE(?, organization_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.cron_expression)
        .bind(&params.app_name)
        .bind(&params.service_name)
        .bind(&params.shell_type)
        .bind(&params.schedule_type)
        .bind(&params.command)
        .bind(&params.script)
        .bind(&params.timezone)
        .bind(&params.enabled)
        .bind(&params.application_id)
        .bind(&params.compose_id)
        .bind(&params.server_id)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM schedules
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
