// Auto-generated by sqlx-gen. Do not edit.

use crate::models::volume_backups::VolumeBackup;

#[derive(Debug, Clone, Default)]
pub struct PaginateVolumeBackupParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationVolumeBackupMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedVolumeBackup {
    pub meta: PaginationVolumeBackupMeta,
    pub data: Vec<VolumeBackup>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertVolumeBackupParams {
    pub name: String,
    pub volume_name: String,
    pub prefix: String,
    pub service_type: Option<String>,
    pub app_name: String,
    pub service_name: Option<String>,
    pub turn_off: Option<i64>,
    pub cron_expression: String,
    pub keep_latest_count: Option<i64>,
    pub enabled: Option<i64>,
    pub destination_id: i64,
    pub organization_id: i64,
    pub application_id: Option<i64>,
    pub postgres_id: Option<i64>,
    pub mysql_id: Option<i64>,
    pub mariadb_id: Option<i64>,
    pub mongo_id: Option<i64>,
    pub redis_id: Option<i64>,
    pub libsql_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteVolumeBackupParams {
    pub name: String,
    pub volume_name: String,
    pub prefix: String,
    pub service_type: String,
    pub app_name: String,
    pub service_name: Option<String>,
    pub turn_off: i64,
    pub cron_expression: String,
    pub keep_latest_count: Option<i64>,
    pub enabled: i64,
    pub destination_id: i64,
    pub organization_id: i64,
    pub application_id: Option<i64>,
    pub postgres_id: Option<i64>,
    pub mysql_id: Option<i64>,
    pub mariadb_id: Option<i64>,
    pub mongo_id: Option<i64>,
    pub redis_id: Option<i64>,
    pub libsql_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateVolumeBackupParams {
    pub name: Option<String>,
    pub volume_name: Option<String>,
    pub prefix: Option<String>,
    pub service_type: Option<String>,
    pub app_name: Option<String>,
    pub service_name: Option<String>,
    pub turn_off: Option<i64>,
    pub cron_expression: Option<String>,
    pub keep_latest_count: Option<i64>,
    pub enabled: Option<i64>,
    pub destination_id: Option<i64>,
    pub organization_id: Option<i64>,
    pub application_id: Option<i64>,
    pub postgres_id: Option<i64>,
    pub mysql_id: Option<i64>,
    pub mariadb_id: Option<i64>,
    pub mongo_id: Option<i64>,
    pub redis_id: Option<i64>,
    pub libsql_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct VolumeBackupRepository {
    pool: sqlx::SqlitePool,
}

impl VolumeBackupRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<VolumeBackup>, sqlx::Error> {
        sqlx::query_as::<_, VolumeBackup>(r#"SELECT * FROM volume_backups"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateVolumeBackupParams,
    ) -> Result<PaginatedVolumeBackup, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM volume_backups"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, VolumeBackup>(
            r#"
            SELECT *
            FROM volume_backups
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedVolumeBackup {
            meta: PaginationVolumeBackupMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<VolumeBackup>, sqlx::Error> {
        sqlx::query_as::<_, VolumeBackup>(
            r#"
            SELECT *
            FROM volume_backups
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertVolumeBackupParams,
    ) -> Result<VolumeBackup, sqlx::Error> {
        sqlx::query_as::<
            _,
            VolumeBackup,
        >(
                r#"
            INSERT INTO volume_backups (name, volume_name, prefix, service_type, app_name, service_name, turn_off, cron_expression, keep_latest_count, enabled, destination_id, organization_id, application_id, postgres_id, mysql_id, mariadb_id, mongo_id, redis_id, libsql_id, compose_id, created_at, updated_at)
            VALUES (?, ?, ?, COALESCE(?, 'APPLICATION'), ?, ?, COALESCE(?, 0), ?, ?, COALESCE(?, 1), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.volume_name)
            .bind(&params.prefix)
            .bind(&params.service_type)
            .bind(&params.app_name)
            .bind(&params.service_name)
            .bind(&params.turn_off)
            .bind(&params.cron_expression)
            .bind(&params.keep_latest_count)
            .bind(&params.enabled)
            .bind(&params.destination_id)
            .bind(&params.organization_id)
            .bind(&params.application_id)
            .bind(&params.postgres_id)
            .bind(&params.mysql_id)
            .bind(&params.mariadb_id)
            .bind(&params.mongo_id)
            .bind(&params.redis_id)
            .bind(&params.libsql_id)
            .bind(&params.compose_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertVolumeBackupParams>,
    ) -> Result<Vec<VolumeBackup>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 22usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 22usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'APPLICATION'"),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "0"),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "1"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "volume_backups",
                "name, volume_name, prefix, service_type, app_name, service_name, turn_off, cron_expression, keep_latest_count, enabled, destination_id, organization_id, application_id, postgres_id, mysql_id, mariadb_id, mongo_id, redis_id, libsql_id, compose_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, VolumeBackup>(&sql);
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.volume_name);
                query = query.bind(&params.prefix);
                query = query.bind(&params.service_type);
                query = query.bind(&params.app_name);
                query = query.bind(&params.service_name);
                query = query.bind(&params.turn_off);
                query = query.bind(&params.cron_expression);
                query = query.bind(&params.keep_latest_count);
                query = query.bind(&params.enabled);
                query = query.bind(&params.destination_id);
                query = query.bind(&params.organization_id);
                query = query.bind(&params.application_id);
                query = query.bind(&params.postgres_id);
                query = query.bind(&params.mysql_id);
                query = query.bind(&params.mariadb_id);
                query = query.bind(&params.mongo_id);
                query = query.bind(&params.redis_id);
                query = query.bind(&params.libsql_id);
                query = query.bind(&params.compose_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteVolumeBackupParams,
    ) -> Result<VolumeBackup, sqlx::Error> {
        sqlx::query_as::<_, VolumeBackup>(
            r#"
            UPDATE volume_backups
            SET
              name = ?,
              volume_name = ?,
              prefix = ?,
              service_type = ?,
              app_name = ?,
              service_name = ?,
              turn_off = ?,
              cron_expression = ?,
              keep_latest_count = ?,
              enabled = ?,
              destination_id = ?,
              organization_id = ?,
              application_id = ?,
              postgres_id = ?,
              mysql_id = ?,
              mariadb_id = ?,
              mongo_id = ?,
              redis_id = ?,
              libsql_id = ?,
              compose_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.volume_name)
        .bind(&params.prefix)
        .bind(&params.service_type)
        .bind(&params.app_name)
        .bind(&params.service_name)
        .bind(&params.turn_off)
        .bind(&params.cron_expression)
        .bind(&params.keep_latest_count)
        .bind(&params.enabled)
        .bind(&params.destination_id)
        .bind(&params.organization_id)
        .bind(&params.application_id)
        .bind(&params.postgres_id)
        .bind(&params.mysql_id)
        .bind(&params.mariadb_id)
        .bind(&params.mongo_id)
        .bind(&params.redis_id)
        .bind(&params.libsql_id)
        .bind(&params.compose_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateVolumeBackupParams,
    ) -> Result<VolumeBackup, sqlx::Error> {
        sqlx::query_as::<_, VolumeBackup>(
            r#"
            UPDATE volume_backups
            SET
              name = COALESCE(?, name),
              volume_name = COALESCE(?, volume_name),
              prefix = COALESCE(?, prefix),
              service_type = COALESCE(?, service_type),
              app_name = COALESCE(?, app_name),
              service_name = COALESCE(?, service_name),
              turn_off = COALESCE(?, turn_off),
              cron_expression = COALESCE(?, cron_expression),
              keep_latest_count = COALESCE(?, keep_latest_count),
              enabled = COALESCE(?, enabled),
              destination_id = COALESCE(?, destination_id),
              organization_id = COALESCE(?, organization_id),
              application_id = COALESCE(?, application_id),
              postgres_id = COALESCE(?, postgres_id),
              mysql_id = COALESCE(?, mysql_id),
              mariadb_id = COALESCE(?, mariadb_id),
              mongo_id = COALESCE(?, mongo_id),
              redis_id = COALESCE(?, redis_id),
              libsql_id = COALESCE(?, libsql_id),
              compose_id = COALESCE(?, compose_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.volume_name)
        .bind(&params.prefix)
        .bind(&params.service_type)
        .bind(&params.app_name)
        .bind(&params.service_name)
        .bind(&params.turn_off)
        .bind(&params.cron_expression)
        .bind(&params.keep_latest_count)
        .bind(&params.enabled)
        .bind(&params.destination_id)
        .bind(&params.organization_id)
        .bind(&params.application_id)
        .bind(&params.postgres_id)
        .bind(&params.mysql_id)
        .bind(&params.mariadb_id)
        .bind(&params.mongo_id)
        .bind(&params.redis_id)
        .bind(&params.libsql_id)
        .bind(&params.compose_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM volume_backups
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
