// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::audit_logs::AuditLog;

#[derive(Debug, Clone, Default)]
pub struct PaginateAuditLogParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationAuditLogMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedAuditLog {
    pub meta: PaginationAuditLogMeta,
    pub data: Vec<AuditLog>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertAuditLogParams {
    pub user_email: String,
    pub user_role: String,
    pub action: String,
    pub resource_type: String,
    pub resource_id: Option<String>,
    pub resource_name: Option<String>,
    pub metadata: Option<String>,
    pub organization_id: Option<i64>,
    pub user_id: Option<i64>,
    pub created_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteAuditLogParams {
    pub user_email: String,
    pub user_role: String,
    pub action: String,
    pub resource_type: String,
    pub resource_id: Option<String>,
    pub resource_name: Option<String>,
    pub metadata: Option<String>,
    pub organization_id: Option<i64>,
    pub user_id: Option<i64>,
    pub created_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateAuditLogParams {
    pub user_email: Option<String>,
    pub user_role: Option<String>,
    pub action: Option<String>,
    pub resource_type: Option<String>,
    pub resource_id: Option<String>,
    pub resource_name: Option<String>,
    pub metadata: Option<String>,
    pub organization_id: Option<i64>,
    pub user_id: Option<i64>,
    pub created_at: Option<i64>,
}

pub struct AuditLogRepository {
    pool: sqlx::SqlitePool,
}

impl AuditLogRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<AuditLog>, sqlx::Error> {
        sqlx::query_as::<_, AuditLog>(r#"SELECT * FROM audit_logs"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateAuditLogParams,
    ) -> Result<PaginatedAuditLog, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM audit_logs"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, AuditLog>(
            r#"
            SELECT *
            FROM audit_logs
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedAuditLog {
            meta: PaginationAuditLogMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<AuditLog>, sqlx::Error> {
        sqlx::query_as::<_, AuditLog>(
            r#"
            SELECT *
            FROM audit_logs
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertAuditLogParams) -> Result<AuditLog, sqlx::Error> {
        sqlx::query_as::<
            _,
            AuditLog,
        >(
                r#"
            INSERT INTO audit_logs (user_email, user_role, action, resource_type, resource_id, resource_name, metadata, organization_id, user_id, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.user_email)
            .bind(&params.user_role)
            .bind(&params.action)
            .bind(&params.resource_type)
            .bind(&params.resource_id)
            .bind(&params.resource_name)
            .bind(&params.metadata)
            .bind(&params.organization_id)
            .bind(&params.user_id)
            .bind(&params.created_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertAuditLogParams>,
    ) -> Result<Vec<AuditLog>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 10usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 10usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "audit_logs",
                "user_email, user_role, action, resource_type, resource_id, resource_name, metadata, organization_id, user_id, created_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, AuditLog>(&sql);
            for params in chunk {
                query = query.bind(&params.user_email);
                query = query.bind(&params.user_role);
                query = query.bind(&params.action);
                query = query.bind(&params.resource_type);
                query = query.bind(&params.resource_id);
                query = query.bind(&params.resource_name);
                query = query.bind(&params.metadata);
                query = query.bind(&params.organization_id);
                query = query.bind(&params.user_id);
                query = query.bind(&params.created_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteAuditLogParams,
    ) -> Result<AuditLog, sqlx::Error> {
        sqlx::query_as::<_, AuditLog>(
            r#"
            UPDATE audit_logs
            SET
              user_email = ?,
              user_role = ?,
              action = ?,
              resource_type = ?,
              resource_id = ?,
              resource_name = ?,
              metadata = ?,
              organization_id = ?,
              user_id = ?,
              created_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.user_email)
        .bind(&params.user_role)
        .bind(&params.action)
        .bind(&params.resource_type)
        .bind(&params.resource_id)
        .bind(&params.resource_name)
        .bind(&params.metadata)
        .bind(&params.organization_id)
        .bind(&params.user_id)
        .bind(&params.created_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateAuditLogParams,
    ) -> Result<AuditLog, sqlx::Error> {
        sqlx::query_as::<_, AuditLog>(
            r#"
            UPDATE audit_logs
            SET
              user_email = COALESCE(?, user_email),
              user_role = COALESCE(?, user_role),
              action = COALESCE(?, action),
              resource_type = COALESCE(?, resource_type),
              resource_id = COALESCE(?, resource_id),
              resource_name = COALESCE(?, resource_name),
              metadata = COALESCE(?, metadata),
              organization_id = COALESCE(?, organization_id),
              user_id = COALESCE(?, user_id),
              created_at = COALESCE(?, created_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.user_email)
        .bind(&params.user_role)
        .bind(&params.action)
        .bind(&params.resource_type)
        .bind(&params.resource_id)
        .bind(&params.resource_name)
        .bind(&params.metadata)
        .bind(&params.organization_id)
        .bind(&params.user_id)
        .bind(&params.created_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM audit_logs
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
