// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::backups::Backup;

#[derive(Debug, Clone, Default)]
pub struct PaginateBackupParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationBackupMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedBackup {
    pub meta: PaginationBackupMeta,
    pub data: Vec<Backup>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertBackupParams {
    pub app_name: String,
    pub schedule: String,
    pub enabled: Option<i64>,
    pub database_name: String,
    pub prefix: String,
    pub service_name: Option<String>,
    pub keep_latest_count: Option<i64>,
    pub backup_type: Option<String>,
    pub database_type: String,
    pub metadata: Option<String>,
    pub compose_id: Option<i64>,
    pub postgres_id: Option<i64>,
    pub mysql_id: Option<i64>,
    pub mariadb_id: Option<i64>,
    pub mongo_id: Option<i64>,
    pub redis_id: Option<i64>,
    pub libsql_id: Option<i64>,
    pub destination_id: i64,
    pub organization_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteBackupParams {
    pub app_name: String,
    pub schedule: String,
    pub enabled: i64,
    pub database_name: String,
    pub prefix: String,
    pub service_name: Option<String>,
    pub keep_latest_count: Option<i64>,
    pub backup_type: String,
    pub database_type: String,
    pub metadata: Option<String>,
    pub compose_id: Option<i64>,
    pub postgres_id: Option<i64>,
    pub mysql_id: Option<i64>,
    pub mariadb_id: Option<i64>,
    pub mongo_id: Option<i64>,
    pub redis_id: Option<i64>,
    pub libsql_id: Option<i64>,
    pub destination_id: i64,
    pub organization_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateBackupParams {
    pub app_name: Option<String>,
    pub schedule: Option<String>,
    pub enabled: Option<i64>,
    pub database_name: Option<String>,
    pub prefix: Option<String>,
    pub service_name: Option<String>,
    pub keep_latest_count: Option<i64>,
    pub backup_type: Option<String>,
    pub database_type: Option<String>,
    pub metadata: Option<String>,
    pub compose_id: Option<i64>,
    pub postgres_id: Option<i64>,
    pub mysql_id: Option<i64>,
    pub mariadb_id: Option<i64>,
    pub mongo_id: Option<i64>,
    pub redis_id: Option<i64>,
    pub libsql_id: Option<i64>,
    pub destination_id: Option<i64>,
    pub organization_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct BackupRepository {
    pool: sqlx::SqlitePool,
}

impl BackupRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Backup>, sqlx::Error> {
        sqlx::query_as::<_, Backup>(r#"SELECT * FROM backups"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateBackupParams,
    ) -> Result<PaginatedBackup, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM backups"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Backup>(
            r#"
            SELECT *
            FROM backups
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedBackup {
            meta: PaginationBackupMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Backup>, sqlx::Error> {
        sqlx::query_as::<_, Backup>(
            r#"
            SELECT *
            FROM backups
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertBackupParams) -> Result<Backup, sqlx::Error> {
        sqlx::query_as::<
            _,
            Backup,
        >(
                r#"
            INSERT INTO backups (app_name, schedule, enabled, database_name, prefix, service_name, keep_latest_count, backup_type, database_type, metadata, compose_id, postgres_id, mysql_id, mariadb_id, mongo_id, redis_id, libsql_id, destination_id, organization_id, created_at, updated_at)
            VALUES (?, ?, COALESCE(?, 1), ?, ?, ?, ?, COALESCE(?, 'DATABASE'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.app_name)
            .bind(&params.schedule)
            .bind(&params.enabled)
            .bind(&params.database_name)
            .bind(&params.prefix)
            .bind(&params.service_name)
            .bind(&params.keep_latest_count)
            .bind(&params.backup_type)
            .bind(&params.database_type)
            .bind(&params.metadata)
            .bind(&params.compose_id)
            .bind(&params.postgres_id)
            .bind(&params.mysql_id)
            .bind(&params.mariadb_id)
            .bind(&params.mongo_id)
            .bind(&params.redis_id)
            .bind(&params.libsql_id)
            .bind(&params.destination_id)
            .bind(&params.organization_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertBackupParams>,
    ) -> Result<Vec<Backup>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 21usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 21usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "1"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'DATABASE'"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "backups",
                "app_name, schedule, enabled, database_name, prefix, service_name, keep_latest_count, backup_type, database_type, metadata, compose_id, postgres_id, mysql_id, mariadb_id, mongo_id, redis_id, libsql_id, destination_id, organization_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Backup>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.app_name);
                query = query.bind(&params.schedule);
                query = query.bind(&params.enabled);
                query = query.bind(&params.database_name);
                query = query.bind(&params.prefix);
                query = query.bind(&params.service_name);
                query = query.bind(&params.keep_latest_count);
                query = query.bind(&params.backup_type);
                query = query.bind(&params.database_type);
                query = query.bind(&params.metadata);
                query = query.bind(&params.compose_id);
                query = query.bind(&params.postgres_id);
                query = query.bind(&params.mysql_id);
                query = query.bind(&params.mariadb_id);
                query = query.bind(&params.mongo_id);
                query = query.bind(&params.redis_id);
                query = query.bind(&params.libsql_id);
                query = query.bind(&params.destination_id);
                query = query.bind(&params.organization_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteBackupParams,
    ) -> Result<Backup, sqlx::Error> {
        sqlx::query_as::<_, Backup>(
            r#"
            UPDATE backups
            SET
              app_name = ?,
              schedule = ?,
              enabled = ?,
              database_name = ?,
              prefix = ?,
              service_name = ?,
              keep_latest_count = ?,
              backup_type = ?,
              database_type = ?,
              metadata = ?,
              compose_id = ?,
              postgres_id = ?,
              mysql_id = ?,
              mariadb_id = ?,
              mongo_id = ?,
              redis_id = ?,
              libsql_id = ?,
              destination_id = ?,
              organization_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.app_name)
        .bind(&params.schedule)
        .bind(&params.enabled)
        .bind(&params.database_name)
        .bind(&params.prefix)
        .bind(&params.service_name)
        .bind(&params.keep_latest_count)
        .bind(&params.backup_type)
        .bind(&params.database_type)
        .bind(&params.metadata)
        .bind(&params.compose_id)
        .bind(&params.postgres_id)
        .bind(&params.mysql_id)
        .bind(&params.mariadb_id)
        .bind(&params.mongo_id)
        .bind(&params.redis_id)
        .bind(&params.libsql_id)
        .bind(&params.destination_id)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateBackupParams,
    ) -> Result<Backup, sqlx::Error> {
        sqlx::query_as::<_, Backup>(
            r#"
            UPDATE backups
            SET
              app_name = COALESCE(?, app_name),
              schedule = COALESCE(?, schedule),
              enabled = COALESCE(?, enabled),
              database_name = COALESCE(?, database_name),
              prefix = COALESCE(?, prefix),
              service_name = COALESCE(?, service_name),
              keep_latest_count = COALESCE(?, keep_latest_count),
              backup_type = COALESCE(?, backup_type),
              database_type = COALESCE(?, database_type),
              metadata = COALESCE(?, metadata),
              compose_id = COALESCE(?, compose_id),
              postgres_id = COALESCE(?, postgres_id),
              mysql_id = COALESCE(?, mysql_id),
              mariadb_id = COALESCE(?, mariadb_id),
              mongo_id = COALESCE(?, mongo_id),
              redis_id = COALESCE(?, redis_id),
              libsql_id = COALESCE(?, libsql_id),
              destination_id = COALESCE(?, destination_id),
              organization_id = COALESCE(?, organization_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.app_name)
        .bind(&params.schedule)
        .bind(&params.enabled)
        .bind(&params.database_name)
        .bind(&params.prefix)
        .bind(&params.service_name)
        .bind(&params.keep_latest_count)
        .bind(&params.backup_type)
        .bind(&params.database_type)
        .bind(&params.metadata)
        .bind(&params.compose_id)
        .bind(&params.postgres_id)
        .bind(&params.mysql_id)
        .bind(&params.mariadb_id)
        .bind(&params.mongo_id)
        .bind(&params.redis_id)
        .bind(&params.libsql_id)
        .bind(&params.destination_id)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM backups
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
