// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::bitbucket_providers::BitbucketProvider;

#[derive(Debug, Clone, Default)]
pub struct PaginateBitbucketProviderParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationBitbucketProviderMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedBitbucketProvider {
    pub meta: PaginationBitbucketProviderMeta,
    pub data: Vec<BitbucketProvider>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertBitbucketProviderParams {
    pub bitbucket_username: Option<String>,
    pub bitbucket_email: Option<String>,
    pub app_password: Option<String>,
    pub api_token: Option<String>,
    pub bitbucket_workspace_name: Option<String>,
    pub git_provider_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteBitbucketProviderParams {
    pub bitbucket_username: Option<String>,
    pub bitbucket_email: Option<String>,
    pub app_password: Option<String>,
    pub api_token: Option<String>,
    pub bitbucket_workspace_name: Option<String>,
    pub git_provider_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateBitbucketProviderParams {
    pub bitbucket_username: Option<String>,
    pub bitbucket_email: Option<String>,
    pub app_password: Option<String>,
    pub api_token: Option<String>,
    pub bitbucket_workspace_name: Option<String>,
    pub git_provider_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct BitbucketProviderRepository {
    pool: sqlx::SqlitePool,
}

impl BitbucketProviderRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<BitbucketProvider>, sqlx::Error> {
        sqlx::query_as::<_, BitbucketProvider>(r#"SELECT * FROM bitbucket_providers"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateBitbucketProviderParams,
    ) -> Result<PaginatedBitbucketProvider, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM bitbucket_providers"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, BitbucketProvider>(
            r#"
            SELECT *
            FROM bitbucket_providers
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedBitbucketProvider {
            meta: PaginationBitbucketProviderMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<BitbucketProvider>, sqlx::Error> {
        sqlx::query_as::<_, BitbucketProvider>(
            r#"
            SELECT *
            FROM bitbucket_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertBitbucketProviderParams,
    ) -> Result<BitbucketProvider, sqlx::Error> {
        sqlx::query_as::<
            _,
            BitbucketProvider,
        >(
                r#"
            INSERT INTO bitbucket_providers (bitbucket_username, bitbucket_email, app_password, api_token, bitbucket_workspace_name, git_provider_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.bitbucket_username)
            .bind(&params.bitbucket_email)
            .bind(&params.app_password)
            .bind(&params.api_token)
            .bind(&params.bitbucket_workspace_name)
            .bind(&params.git_provider_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertBitbucketProviderParams>,
    ) -> Result<Vec<BitbucketProvider>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 8usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 8usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "bitbucket_providers",
                "bitbucket_username, bitbucket_email, app_password, api_token, bitbucket_workspace_name, git_provider_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, BitbucketProvider>(&sql);
            for params in chunk {
                query = query.bind(&params.bitbucket_username);
                query = query.bind(&params.bitbucket_email);
                query = query.bind(&params.app_password);
                query = query.bind(&params.api_token);
                query = query.bind(&params.bitbucket_workspace_name);
                query = query.bind(&params.git_provider_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteBitbucketProviderParams,
    ) -> Result<BitbucketProvider, sqlx::Error> {
        sqlx::query_as::<_, BitbucketProvider>(
            r#"
            UPDATE bitbucket_providers
            SET
              bitbucket_username = ?,
              bitbucket_email = ?,
              app_password = ?,
              api_token = ?,
              bitbucket_workspace_name = ?,
              git_provider_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.bitbucket_username)
        .bind(&params.bitbucket_email)
        .bind(&params.app_password)
        .bind(&params.api_token)
        .bind(&params.bitbucket_workspace_name)
        .bind(&params.git_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateBitbucketProviderParams,
    ) -> Result<BitbucketProvider, sqlx::Error> {
        sqlx::query_as::<_, BitbucketProvider>(
            r#"
            UPDATE bitbucket_providers
            SET
              bitbucket_username = COALESCE(?, bitbucket_username),
              bitbucket_email = COALESCE(?, bitbucket_email),
              app_password = COALESCE(?, app_password),
              api_token = COALESCE(?, api_token),
              bitbucket_workspace_name = COALESCE(?, bitbucket_workspace_name),
              git_provider_id = COALESCE(?, git_provider_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.bitbucket_username)
        .bind(&params.bitbucket_email)
        .bind(&params.app_password)
        .bind(&params.api_token)
        .bind(&params.bitbucket_workspace_name)
        .bind(&params.git_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM bitbucket_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
