// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::container_metrics::ContainerMetric;

#[derive(Debug, Clone, Default)]
pub struct PaginateContainerMetricParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationContainerMetricMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedContainerMetric {
    pub meta: PaginationContainerMetricMeta,
    pub data: Vec<ContainerMetric>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertContainerMetricParams {
    pub timestamp: i64,
    pub container_id: String,
    pub container_name: String,
    pub metrics_json: String,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteContainerMetricParams {
    pub timestamp: i64,
    pub container_id: String,
    pub container_name: String,
    pub metrics_json: String,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateContainerMetricParams {
    pub timestamp: Option<i64>,
    pub container_id: Option<String>,
    pub container_name: Option<String>,
    pub metrics_json: Option<String>,
}

pub struct ContainerMetricRepository {
    pool: sqlx::SqlitePool,
}

impl ContainerMetricRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<ContainerMetric>, sqlx::Error> {
        sqlx::query_as::<_, ContainerMetric>(r#"SELECT * FROM container_metrics"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateContainerMetricParams,
    ) -> Result<PaginatedContainerMetric, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM container_metrics"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, ContainerMetric>(
            r#"
            SELECT *
            FROM container_metrics
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedContainerMetric {
            meta: PaginationContainerMetricMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<ContainerMetric>, sqlx::Error> {
        sqlx::query_as::<_, ContainerMetric>(
            r#"
            SELECT *
            FROM container_metrics
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertContainerMetricParams,
    ) -> Result<ContainerMetric, sqlx::Error> {
        sqlx::query_as::<_, ContainerMetric>(
            r#"
            INSERT INTO container_metrics (timestamp, container_id, container_name, metrics_json)
            VALUES (?, ?, ?, ?)
            RETURNING *
        "#,
        )
        .bind(&params.timestamp)
        .bind(&params.container_id)
        .bind(&params.container_name)
        .bind(&params.metrics_json)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertContainerMetricParams>,
    ) -> Result<Vec<ContainerMetric>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 4usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 4usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "container_metrics",
                "timestamp, container_id, container_name, metrics_json",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, ContainerMetric>(&sql);
            for params in chunk {
                query = query.bind(&params.timestamp);
                query = query.bind(&params.container_id);
                query = query.bind(&params.container_name);
                query = query.bind(&params.metrics_json);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteContainerMetricParams,
    ) -> Result<ContainerMetric, sqlx::Error> {
        sqlx::query_as::<_, ContainerMetric>(
            r#"
            UPDATE container_metrics
            SET
              timestamp = ?,
              container_id = ?,
              container_name = ?,
              metrics_json = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.timestamp)
        .bind(&params.container_id)
        .bind(&params.container_name)
        .bind(&params.metrics_json)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateContainerMetricParams,
    ) -> Result<ContainerMetric, sqlx::Error> {
        sqlx::query_as::<_, ContainerMetric>(
            r#"
            UPDATE container_metrics
            SET
              timestamp = COALESCE(?, timestamp),
              container_id = COALESCE(?, container_id),
              container_name = COALESCE(?, container_name),
              metrics_json = COALESCE(?, metrics_json)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.timestamp)
        .bind(&params.container_id)
        .bind(&params.container_name)
        .bind(&params.metrics_json)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM container_metrics
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
