// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::deployments::Deployment;

#[derive(Debug, Clone, Default)]
pub struct PaginateDeploymentParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationDeploymentMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedDeployment {
    pub meta: PaginationDeploymentMeta,
    pub data: Vec<Deployment>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertDeploymentParams {
    pub title: String,
    pub description: Option<String>,
    pub status: Option<String>,
    pub log_path: String,
    pub pid: Option<String>,
    pub error_message: Option<String>,
    pub is_preview_deployment: Option<i64>,
    pub started_at: Option<i64>,
    pub finished_at: Option<i64>,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub server_id: Option<i64>,
    pub created_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteDeploymentParams {
    pub title: String,
    pub description: Option<String>,
    pub status: String,
    pub log_path: String,
    pub pid: Option<String>,
    pub error_message: Option<String>,
    pub is_preview_deployment: i64,
    pub started_at: Option<i64>,
    pub finished_at: Option<i64>,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub server_id: Option<i64>,
    pub created_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateDeploymentParams {
    pub title: Option<String>,
    pub description: Option<String>,
    pub status: Option<String>,
    pub log_path: Option<String>,
    pub pid: Option<String>,
    pub error_message: Option<String>,
    pub is_preview_deployment: Option<i64>,
    pub started_at: Option<i64>,
    pub finished_at: Option<i64>,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub server_id: Option<i64>,
    pub created_at: Option<i64>,
}

pub struct DeploymentRepository {
    pool: sqlx::SqlitePool,
}

impl DeploymentRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Deployment>, sqlx::Error> {
        sqlx::query_as::<_, Deployment>(r#"SELECT * FROM deployments"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateDeploymentParams,
    ) -> Result<PaginatedDeployment, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM deployments"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Deployment>(
            r#"
            SELECT *
            FROM deployments
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedDeployment {
            meta: PaginationDeploymentMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Deployment>, sqlx::Error> {
        sqlx::query_as::<_, Deployment>(
            r#"
            SELECT *
            FROM deployments
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertDeploymentParams) -> Result<Deployment, sqlx::Error> {
        sqlx::query_as::<
            _,
            Deployment,
        >(
                r#"
            INSERT INTO deployments (title, description, status, log_path, pid, error_message, is_preview_deployment, started_at, finished_at, application_id, compose_id, server_id, created_at)
            VALUES (?, ?, COALESCE(?, 'RUNNING'), ?, ?, ?, COALESCE(?, 0), ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.title)
            .bind(&params.description)
            .bind(&params.status)
            .bind(&params.log_path)
            .bind(&params.pid)
            .bind(&params.error_message)
            .bind(&params.is_preview_deployment)
            .bind(&params.started_at)
            .bind(&params.finished_at)
            .bind(&params.application_id)
            .bind(&params.compose_id)
            .bind(&params.server_id)
            .bind(&params.created_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertDeploymentParams>,
    ) -> Result<Vec<Deployment>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 13usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 13usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'RUNNING'"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "0"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "deployments",
                "title, description, status, log_path, pid, error_message, is_preview_deployment, started_at, finished_at, application_id, compose_id, server_id, created_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Deployment>(&sql);
            for params in chunk {
                query = query.bind(&params.title);
                query = query.bind(&params.description);
                query = query.bind(&params.status);
                query = query.bind(&params.log_path);
                query = query.bind(&params.pid);
                query = query.bind(&params.error_message);
                query = query.bind(&params.is_preview_deployment);
                query = query.bind(&params.started_at);
                query = query.bind(&params.finished_at);
                query = query.bind(&params.application_id);
                query = query.bind(&params.compose_id);
                query = query.bind(&params.server_id);
                query = query.bind(&params.created_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteDeploymentParams,
    ) -> Result<Deployment, sqlx::Error> {
        sqlx::query_as::<_, Deployment>(
            r#"
            UPDATE deployments
            SET
              title = ?,
              description = ?,
              status = ?,
              log_path = ?,
              pid = ?,
              error_message = ?,
              is_preview_deployment = ?,
              started_at = ?,
              finished_at = ?,
              application_id = ?,
              compose_id = ?,
              server_id = ?,
              created_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.title)
        .bind(&params.description)
        .bind(&params.status)
        .bind(&params.log_path)
        .bind(&params.pid)
        .bind(&params.error_message)
        .bind(&params.is_preview_deployment)
        .bind(&params.started_at)
        .bind(&params.finished_at)
        .bind(&params.application_id)
        .bind(&params.compose_id)
        .bind(&params.server_id)
        .bind(&params.created_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateDeploymentParams,
    ) -> Result<Deployment, sqlx::Error> {
        sqlx::query_as::<_, Deployment>(
            r#"
            UPDATE deployments
            SET
              title = COALESCE(?, title),
              description = COALESCE(?, description),
              status = COALESCE(?, status),
              log_path = COALESCE(?, log_path),
              pid = COALESCE(?, pid),
              error_message = COALESCE(?, error_message),
              is_preview_deployment = COALESCE(?, is_preview_deployment),
              started_at = COALESCE(?, started_at),
              finished_at = COALESCE(?, finished_at),
              application_id = COALESCE(?, application_id),
              compose_id = COALESCE(?, compose_id),
              server_id = COALESCE(?, server_id),
              created_at = COALESCE(?, created_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.title)
        .bind(&params.description)
        .bind(&params.status)
        .bind(&params.log_path)
        .bind(&params.pid)
        .bind(&params.error_message)
        .bind(&params.is_preview_deployment)
        .bind(&params.started_at)
        .bind(&params.finished_at)
        .bind(&params.application_id)
        .bind(&params.compose_id)
        .bind(&params.server_id)
        .bind(&params.created_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM deployments
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
