// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::domains::Domain;

#[derive(Debug, Clone, Default)]
pub struct PaginateDomainParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationDomainMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedDomain {
    pub meta: PaginationDomainMeta,
    pub data: Vec<Domain>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertDomainParams {
    pub host: String,
    pub https: Option<i64>,
    pub port: Option<i64>,
    pub path: Option<String>,
    pub internal_path: Option<String>,
    pub custom_entrypoint: Option<String>,
    pub service_name: Option<String>,
    pub custom_cert_resolver: Option<String>,
    pub strip_path: Option<i64>,
    pub middlewares: Option<String>,
    pub domain_type: Option<String>,
    pub certificate_type: Option<String>,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteDomainParams {
    pub host: String,
    pub https: i64,
    pub port: Option<i64>,
    pub path: Option<String>,
    pub internal_path: Option<String>,
    pub custom_entrypoint: Option<String>,
    pub service_name: Option<String>,
    pub custom_cert_resolver: Option<String>,
    pub strip_path: i64,
    pub middlewares: String,
    pub domain_type: String,
    pub certificate_type: String,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateDomainParams {
    pub host: Option<String>,
    pub https: Option<i64>,
    pub port: Option<i64>,
    pub path: Option<String>,
    pub internal_path: Option<String>,
    pub custom_entrypoint: Option<String>,
    pub service_name: Option<String>,
    pub custom_cert_resolver: Option<String>,
    pub strip_path: Option<i64>,
    pub middlewares: Option<String>,
    pub domain_type: Option<String>,
    pub certificate_type: Option<String>,
    pub application_id: Option<i64>,
    pub compose_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct DomainRepository {
    pool: sqlx::SqlitePool,
}

impl DomainRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Domain>, sqlx::Error> {
        sqlx::query_as::<_, Domain>(r#"SELECT * FROM domains"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateDomainParams,
    ) -> Result<PaginatedDomain, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM domains"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Domain>(
            r#"
            SELECT *
            FROM domains
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedDomain {
            meta: PaginationDomainMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Domain>, sqlx::Error> {
        sqlx::query_as::<_, Domain>(
            r#"
            SELECT *
            FROM domains
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertDomainParams) -> Result<Domain, sqlx::Error> {
        sqlx::query_as::<
            _,
            Domain,
        >(
                r#"
            INSERT INTO domains (host, https, port, path, internal_path, custom_entrypoint, service_name, custom_cert_resolver, strip_path, middlewares, domain_type, certificate_type, application_id, compose_id, created_at, updated_at)
            VALUES (?, COALESCE(?, 0), COALESCE(?, 3000), COALESCE(?, '/'), COALESCE(?, '/'), ?, ?, ?, COALESCE(?, 0), COALESCE(?, '[]'), COALESCE(?, 'APPLICATION'), COALESCE(?, 'NONE'), ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.host)
            .bind(&params.https)
            .bind(&params.port)
            .bind(&params.path)
            .bind(&params.internal_path)
            .bind(&params.custom_entrypoint)
            .bind(&params.service_name)
            .bind(&params.custom_cert_resolver)
            .bind(&params.strip_path)
            .bind(&params.middlewares)
            .bind(&params.domain_type)
            .bind(&params.certificate_type)
            .bind(&params.application_id)
            .bind(&params.compose_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertDomainParams>,
    ) -> Result<Vec<Domain>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 16usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 16usize;
                let placeholders = vec![
                    "?".to_string(),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "3000"),
                    format!("COALESCE(?, {})", "'/'"),
                    format!("COALESCE(?, {})", "'/'"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "'[]'"),
                    format!("COALESCE(?, {})", "'APPLICATION'"),
                    format!("COALESCE(?, {})", "'NONE'"),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "domains",
                "host, https, port, path, internal_path, custom_entrypoint, service_name, custom_cert_resolver, strip_path, middlewares, domain_type, certificate_type, application_id, compose_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Domain>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.host);
                query = query.bind(&params.https);
                query = query.bind(&params.port);
                query = query.bind(&params.path);
                query = query.bind(&params.internal_path);
                query = query.bind(&params.custom_entrypoint);
                query = query.bind(&params.service_name);
                query = query.bind(&params.custom_cert_resolver);
                query = query.bind(&params.strip_path);
                query = query.bind(&params.middlewares);
                query = query.bind(&params.domain_type);
                query = query.bind(&params.certificate_type);
                query = query.bind(&params.application_id);
                query = query.bind(&params.compose_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteDomainParams,
    ) -> Result<Domain, sqlx::Error> {
        sqlx::query_as::<_, Domain>(
            r#"
            UPDATE domains
            SET
              host = ?,
              https = ?,
              port = ?,
              path = ?,
              internal_path = ?,
              custom_entrypoint = ?,
              service_name = ?,
              custom_cert_resolver = ?,
              strip_path = ?,
              middlewares = ?,
              domain_type = ?,
              certificate_type = ?,
              application_id = ?,
              compose_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.host)
        .bind(&params.https)
        .bind(&params.port)
        .bind(&params.path)
        .bind(&params.internal_path)
        .bind(&params.custom_entrypoint)
        .bind(&params.service_name)
        .bind(&params.custom_cert_resolver)
        .bind(&params.strip_path)
        .bind(&params.middlewares)
        .bind(&params.domain_type)
        .bind(&params.certificate_type)
        .bind(&params.application_id)
        .bind(&params.compose_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateDomainParams,
    ) -> Result<Domain, sqlx::Error> {
        sqlx::query_as::<_, Domain>(
            r#"
            UPDATE domains
            SET
              host = COALESCE(?, host),
              https = COALESCE(?, https),
              port = COALESCE(?, port),
              path = COALESCE(?, path),
              internal_path = COALESCE(?, internal_path),
              custom_entrypoint = COALESCE(?, custom_entrypoint),
              service_name = COALESCE(?, service_name),
              custom_cert_resolver = COALESCE(?, custom_cert_resolver),
              strip_path = COALESCE(?, strip_path),
              middlewares = COALESCE(?, middlewares),
              domain_type = COALESCE(?, domain_type),
              certificate_type = COALESCE(?, certificate_type),
              application_id = COALESCE(?, application_id),
              compose_id = COALESCE(?, compose_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.host)
        .bind(&params.https)
        .bind(&params.port)
        .bind(&params.path)
        .bind(&params.internal_path)
        .bind(&params.custom_entrypoint)
        .bind(&params.service_name)
        .bind(&params.custom_cert_resolver)
        .bind(&params.strip_path)
        .bind(&params.middlewares)
        .bind(&params.domain_type)
        .bind(&params.certificate_type)
        .bind(&params.application_id)
        .bind(&params.compose_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM domains
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
