// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::environments::Environment;

#[derive(Debug, Clone, Default)]
pub struct PaginateEnvironmentParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationEnvironmentMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedEnvironment {
    pub meta: PaginationEnvironmentMeta,
    pub data: Vec<Environment>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertEnvironmentParams {
    pub name: String,
    pub description: Option<String>,
    pub env_var: Option<String>,
    pub is_default: Option<i64>,
    pub project_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteEnvironmentParams {
    pub name: String,
    pub description: Option<String>,
    pub env_var: String,
    pub is_default: i64,
    pub project_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateEnvironmentParams {
    pub name: Option<String>,
    pub description: Option<String>,
    pub env_var: Option<String>,
    pub is_default: Option<i64>,
    pub project_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct EnvironmentRepository {
    pool: sqlx::SqlitePool,
}

impl EnvironmentRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Environment>, sqlx::Error> {
        sqlx::query_as::<_, Environment>(r#"SELECT * FROM environments"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateEnvironmentParams,
    ) -> Result<PaginatedEnvironment, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM environments"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Environment>(
            r#"
            SELECT *
            FROM environments
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedEnvironment {
            meta: PaginationEnvironmentMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Environment>, sqlx::Error> {
        sqlx::query_as::<_, Environment>(
            r#"
            SELECT *
            FROM environments
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertEnvironmentParams,
    ) -> Result<Environment, sqlx::Error> {
        sqlx::query_as::<
            _,
            Environment,
        >(
                r#"
            INSERT INTO environments (name, description, env_var, is_default, project_id, created_at, updated_at)
            VALUES (?, ?, COALESCE(?, ''), COALESCE(?, 0), ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.description)
            .bind(&params.env_var)
            .bind(&params.is_default)
            .bind(&params.project_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertEnvironmentParams>,
    ) -> Result<Vec<Environment>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 7usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 7usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "''"),
                    format!("COALESCE(?, {})", "0"),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "environments",
                "name, description, env_var, is_default, project_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Environment>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.description);
                query = query.bind(&params.env_var);
                query = query.bind(&params.is_default);
                query = query.bind(&params.project_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteEnvironmentParams,
    ) -> Result<Environment, sqlx::Error> {
        sqlx::query_as::<_, Environment>(
            r#"
            UPDATE environments
            SET
              name = ?,
              description = ?,
              env_var = ?,
              is_default = ?,
              project_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.env_var)
        .bind(&params.is_default)
        .bind(&params.project_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateEnvironmentParams,
    ) -> Result<Environment, sqlx::Error> {
        sqlx::query_as::<_, Environment>(
            r#"
            UPDATE environments
            SET
              name = COALESCE(?, name),
              description = COALESCE(?, description),
              env_var = COALESCE(?, env_var),
              is_default = COALESCE(?, is_default),
              project_id = COALESCE(?, project_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.env_var)
        .bind(&params.is_default)
        .bind(&params.project_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM environments
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
