// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::gitea_providers::GiteaProvider;

#[derive(Debug, Clone, Default)]
pub struct PaginateGiteaProviderParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationGiteaProviderMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedGiteaProvider {
    pub meta: PaginationGiteaProviderMeta,
    pub data: Vec<GiteaProvider>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertGiteaProviderParams {
    pub gitea_url: Option<String>,
    pub gitea_internal_url: Option<String>,
    pub redirect_uri: Option<String>,
    pub client_id: Option<String>,
    pub client_secret: Option<String>,
    pub access_token: Option<String>,
    pub refresh_token: Option<String>,
    pub expires_at: Option<i64>,
    pub scopes: Option<String>,
    pub last_authenticated_at: Option<i64>,
    pub git_provider_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteGiteaProviderParams {
    pub gitea_url: String,
    pub gitea_internal_url: Option<String>,
    pub redirect_uri: Option<String>,
    pub client_id: Option<String>,
    pub client_secret: Option<String>,
    pub access_token: Option<String>,
    pub refresh_token: Option<String>,
    pub expires_at: Option<i64>,
    pub scopes: Option<String>,
    pub last_authenticated_at: Option<i64>,
    pub git_provider_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateGiteaProviderParams {
    pub gitea_url: Option<String>,
    pub gitea_internal_url: Option<String>,
    pub redirect_uri: Option<String>,
    pub client_id: Option<String>,
    pub client_secret: Option<String>,
    pub access_token: Option<String>,
    pub refresh_token: Option<String>,
    pub expires_at: Option<i64>,
    pub scopes: Option<String>,
    pub last_authenticated_at: Option<i64>,
    pub git_provider_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct GiteaProviderRepository {
    pool: sqlx::SqlitePool,
}

impl GiteaProviderRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<GiteaProvider>, sqlx::Error> {
        sqlx::query_as::<_, GiteaProvider>(r#"SELECT * FROM gitea_providers"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateGiteaProviderParams,
    ) -> Result<PaginatedGiteaProvider, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM gitea_providers"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, GiteaProvider>(
            r#"
            SELECT *
            FROM gitea_providers
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedGiteaProvider {
            meta: PaginationGiteaProviderMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<GiteaProvider>, sqlx::Error> {
        sqlx::query_as::<_, GiteaProvider>(
            r#"
            SELECT *
            FROM gitea_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertGiteaProviderParams,
    ) -> Result<GiteaProvider, sqlx::Error> {
        sqlx::query_as::<
            _,
            GiteaProvider,
        >(
                r#"
            INSERT INTO gitea_providers (gitea_url, gitea_internal_url, redirect_uri, client_id, client_secret, access_token, refresh_token, expires_at, scopes, last_authenticated_at, git_provider_id, created_at, updated_at)
            VALUES (COALESCE(?, 'https://gitea.com'), ?, ?, ?, ?, ?, ?, ?, COALESCE(?, 'repo,repo:status,read:user,read:org'), ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.gitea_url)
            .bind(&params.gitea_internal_url)
            .bind(&params.redirect_uri)
            .bind(&params.client_id)
            .bind(&params.client_secret)
            .bind(&params.access_token)
            .bind(&params.refresh_token)
            .bind(&params.expires_at)
            .bind(&params.scopes)
            .bind(&params.last_authenticated_at)
            .bind(&params.git_provider_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertGiteaProviderParams>,
    ) -> Result<Vec<GiteaProvider>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 13usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 13usize;
                let placeholders = vec![
                    format!("COALESCE(?, {})", "'https://gitea.com'"),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'repo,repo:status,read:user,read:org'"),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "gitea_providers",
                "gitea_url, gitea_internal_url, redirect_uri, client_id, client_secret, access_token, refresh_token, expires_at, scopes, last_authenticated_at, git_provider_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, GiteaProvider>(&sql);
            for params in chunk {
                query = query.bind(&params.gitea_url);
                query = query.bind(&params.gitea_internal_url);
                query = query.bind(&params.redirect_uri);
                query = query.bind(&params.client_id);
                query = query.bind(&params.client_secret);
                query = query.bind(&params.access_token);
                query = query.bind(&params.refresh_token);
                query = query.bind(&params.expires_at);
                query = query.bind(&params.scopes);
                query = query.bind(&params.last_authenticated_at);
                query = query.bind(&params.git_provider_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteGiteaProviderParams,
    ) -> Result<GiteaProvider, sqlx::Error> {
        sqlx::query_as::<_, GiteaProvider>(
            r#"
            UPDATE gitea_providers
            SET
              gitea_url = ?,
              gitea_internal_url = ?,
              redirect_uri = ?,
              client_id = ?,
              client_secret = ?,
              access_token = ?,
              refresh_token = ?,
              expires_at = ?,
              scopes = ?,
              last_authenticated_at = ?,
              git_provider_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.gitea_url)
        .bind(&params.gitea_internal_url)
        .bind(&params.redirect_uri)
        .bind(&params.client_id)
        .bind(&params.client_secret)
        .bind(&params.access_token)
        .bind(&params.refresh_token)
        .bind(&params.expires_at)
        .bind(&params.scopes)
        .bind(&params.last_authenticated_at)
        .bind(&params.git_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateGiteaProviderParams,
    ) -> Result<GiteaProvider, sqlx::Error> {
        sqlx::query_as::<_, GiteaProvider>(
            r#"
            UPDATE gitea_providers
            SET
              gitea_url = COALESCE(?, gitea_url),
              gitea_internal_url = COALESCE(?, gitea_internal_url),
              redirect_uri = COALESCE(?, redirect_uri),
              client_id = COALESCE(?, client_id),
              client_secret = COALESCE(?, client_secret),
              access_token = COALESCE(?, access_token),
              refresh_token = COALESCE(?, refresh_token),
              expires_at = COALESCE(?, expires_at),
              scopes = COALESCE(?, scopes),
              last_authenticated_at = COALESCE(?, last_authenticated_at),
              git_provider_id = COALESCE(?, git_provider_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.gitea_url)
        .bind(&params.gitea_internal_url)
        .bind(&params.redirect_uri)
        .bind(&params.client_id)
        .bind(&params.client_secret)
        .bind(&params.access_token)
        .bind(&params.refresh_token)
        .bind(&params.expires_at)
        .bind(&params.scopes)
        .bind(&params.last_authenticated_at)
        .bind(&params.git_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM gitea_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
