// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::github_providers::GithubProvider;

#[derive(Debug, Clone, Default)]
pub struct PaginateGithubProviderParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationGithubProviderMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedGithubProvider {
    pub meta: PaginationGithubProviderMeta,
    pub data: Vec<GithubProvider>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertGithubProviderParams {
    pub github_app_name: Option<String>,
    pub github_app_id: Option<i64>,
    pub github_client_id: Option<String>,
    pub github_client_secret: Option<String>,
    pub github_installation_id: Option<String>,
    pub github_private_key: Option<String>,
    pub github_webhook_secret: Option<String>,
    pub git_provider_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteGithubProviderParams {
    pub github_app_name: Option<String>,
    pub github_app_id: Option<i64>,
    pub github_client_id: Option<String>,
    pub github_client_secret: Option<String>,
    pub github_installation_id: Option<String>,
    pub github_private_key: Option<String>,
    pub github_webhook_secret: Option<String>,
    pub git_provider_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateGithubProviderParams {
    pub github_app_name: Option<String>,
    pub github_app_id: Option<i64>,
    pub github_client_id: Option<String>,
    pub github_client_secret: Option<String>,
    pub github_installation_id: Option<String>,
    pub github_private_key: Option<String>,
    pub github_webhook_secret: Option<String>,
    pub git_provider_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct GithubProviderRepository {
    pool: sqlx::SqlitePool,
}

impl GithubProviderRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<GithubProvider>, sqlx::Error> {
        sqlx::query_as::<_, GithubProvider>(r#"SELECT * FROM github_providers"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateGithubProviderParams,
    ) -> Result<PaginatedGithubProvider, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM github_providers"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, GithubProvider>(
            r#"
            SELECT *
            FROM github_providers
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedGithubProvider {
            meta: PaginationGithubProviderMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<GithubProvider>, sqlx::Error> {
        sqlx::query_as::<_, GithubProvider>(
            r#"
            SELECT *
            FROM github_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertGithubProviderParams,
    ) -> Result<GithubProvider, sqlx::Error> {
        sqlx::query_as::<
            _,
            GithubProvider,
        >(
                r#"
            INSERT INTO github_providers (github_app_name, github_app_id, github_client_id, github_client_secret, github_installation_id, github_private_key, github_webhook_secret, git_provider_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.github_app_name)
            .bind(&params.github_app_id)
            .bind(&params.github_client_id)
            .bind(&params.github_client_secret)
            .bind(&params.github_installation_id)
            .bind(&params.github_private_key)
            .bind(&params.github_webhook_secret)
            .bind(&params.git_provider_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertGithubProviderParams>,
    ) -> Result<Vec<GithubProvider>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 10usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 10usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "github_providers",
                "github_app_name, github_app_id, github_client_id, github_client_secret, github_installation_id, github_private_key, github_webhook_secret, git_provider_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, GithubProvider>(&sql);
            for params in chunk {
                query = query.bind(&params.github_app_name);
                query = query.bind(&params.github_app_id);
                query = query.bind(&params.github_client_id);
                query = query.bind(&params.github_client_secret);
                query = query.bind(&params.github_installation_id);
                query = query.bind(&params.github_private_key);
                query = query.bind(&params.github_webhook_secret);
                query = query.bind(&params.git_provider_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteGithubProviderParams,
    ) -> Result<GithubProvider, sqlx::Error> {
        sqlx::query_as::<_, GithubProvider>(
            r#"
            UPDATE github_providers
            SET
              github_app_name = ?,
              github_app_id = ?,
              github_client_id = ?,
              github_client_secret = ?,
              github_installation_id = ?,
              github_private_key = ?,
              github_webhook_secret = ?,
              git_provider_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.github_app_name)
        .bind(&params.github_app_id)
        .bind(&params.github_client_id)
        .bind(&params.github_client_secret)
        .bind(&params.github_installation_id)
        .bind(&params.github_private_key)
        .bind(&params.github_webhook_secret)
        .bind(&params.git_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateGithubProviderParams,
    ) -> Result<GithubProvider, sqlx::Error> {
        sqlx::query_as::<_, GithubProvider>(
            r#"
            UPDATE github_providers
            SET
              github_app_name = COALESCE(?, github_app_name),
              github_app_id = COALESCE(?, github_app_id),
              github_client_id = COALESCE(?, github_client_id),
              github_client_secret = COALESCE(?, github_client_secret),
              github_installation_id = COALESCE(?, github_installation_id),
              github_private_key = COALESCE(?, github_private_key),
              github_webhook_secret = COALESCE(?, github_webhook_secret),
              git_provider_id = COALESCE(?, git_provider_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.github_app_name)
        .bind(&params.github_app_id)
        .bind(&params.github_client_id)
        .bind(&params.github_client_secret)
        .bind(&params.github_installation_id)
        .bind(&params.github_private_key)
        .bind(&params.github_webhook_secret)
        .bind(&params.git_provider_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM github_providers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
