// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::notif_telegram::NotifTelegram;

#[derive(Debug, Clone, Default)]
pub struct PaginateNotifTelegramParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationNotifTelegramMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedNotifTelegram {
    pub meta: PaginationNotifTelegramMeta,
    pub data: Vec<NotifTelegram>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertNotifTelegramParams {
    pub bot_token: String,
    pub chat_id: String,
    pub message_thread_id: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteNotifTelegramParams {
    pub bot_token: String,
    pub chat_id: String,
    pub message_thread_id: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateNotifTelegramParams {
    pub bot_token: Option<String>,
    pub chat_id: Option<String>,
    pub message_thread_id: Option<String>,
}

pub struct NotifTelegramRepository {
    pool: sqlx::SqlitePool,
}

impl NotifTelegramRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<NotifTelegram>, sqlx::Error> {
        sqlx::query_as::<_, NotifTelegram>(r#"SELECT * FROM notif_telegram"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateNotifTelegramParams,
    ) -> Result<PaginatedNotifTelegram, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM notif_telegram"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, NotifTelegram>(
            r#"
            SELECT *
            FROM notif_telegram
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedNotifTelegram {
            meta: PaginationNotifTelegramMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<NotifTelegram>, sqlx::Error> {
        sqlx::query_as::<_, NotifTelegram>(
            r#"
            SELECT *
            FROM notif_telegram
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertNotifTelegramParams,
    ) -> Result<NotifTelegram, sqlx::Error> {
        sqlx::query_as::<_, NotifTelegram>(
            r#"
            INSERT INTO notif_telegram (bot_token, chat_id, message_thread_id)
            VALUES (?, ?, ?)
            RETURNING *
        "#,
        )
        .bind(&params.bot_token)
        .bind(&params.chat_id)
        .bind(&params.message_thread_id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertNotifTelegramParams>,
    ) -> Result<Vec<NotifTelegram>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 3usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 3usize;
                let placeholders = vec!["?".to_string(), "?".to_string(), "?".to_string()];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "notif_telegram",
                "bot_token, chat_id, message_thread_id",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, NotifTelegram>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.bot_token);
                query = query.bind(&params.chat_id);
                query = query.bind(&params.message_thread_id);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteNotifTelegramParams,
    ) -> Result<NotifTelegram, sqlx::Error> {
        sqlx::query_as::<_, NotifTelegram>(
            r#"
            UPDATE notif_telegram
            SET
              bot_token = ?,
              chat_id = ?,
              message_thread_id = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.bot_token)
        .bind(&params.chat_id)
        .bind(&params.message_thread_id)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateNotifTelegramParams,
    ) -> Result<NotifTelegram, sqlx::Error> {
        sqlx::query_as::<_, NotifTelegram>(
            r#"
            UPDATE notif_telegram
            SET
              bot_token = COALESCE(?, bot_token),
              chat_id = COALESCE(?, chat_id),
              message_thread_id = COALESCE(?, message_thread_id)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.bot_token)
        .bind(&params.chat_id)
        .bind(&params.message_thread_id)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM notif_telegram
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
