// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::notif_discord::NotifDiscord;

#[derive(Debug, Clone, Default)]
pub struct PaginateNotifDiscordParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationNotifDiscordMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedNotifDiscord {
    pub meta: PaginationNotifDiscordMeta,
    pub data: Vec<NotifDiscord>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertNotifDiscordParams {
    pub webhook_url: String,
    pub decoration: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteNotifDiscordParams {
    pub webhook_url: String,
    pub decoration: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateNotifDiscordParams {
    pub webhook_url: Option<String>,
    pub decoration: Option<i64>,
}

pub struct NotifDiscordRepository {
    pool: sqlx::SqlitePool,
}

impl NotifDiscordRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<NotifDiscord>, sqlx::Error> {
        sqlx::query_as::<_, NotifDiscord>(r#"SELECT * FROM notif_discord"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateNotifDiscordParams,
    ) -> Result<PaginatedNotifDiscord, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM notif_discord"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, NotifDiscord>(
            r#"
            SELECT *
            FROM notif_discord
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedNotifDiscord {
            meta: PaginationNotifDiscordMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<NotifDiscord>, sqlx::Error> {
        sqlx::query_as::<_, NotifDiscord>(
            r#"
            SELECT *
            FROM notif_discord
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertNotifDiscordParams,
    ) -> Result<NotifDiscord, sqlx::Error> {
        sqlx::query_as::<_, NotifDiscord>(
            r#"
            INSERT INTO notif_discord (webhook_url, decoration)
            VALUES (?, COALESCE(?, 0))
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .bind(&params.decoration)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertNotifDiscordParams>,
    ) -> Result<Vec<NotifDiscord>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 2usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 2usize;
                let placeholders = vec!["?".to_string(), format!("COALESCE(?, {})", "0")];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "notif_discord",
                "webhook_url, decoration",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, NotifDiscord>(&sql);
            for params in chunk {
                query = query.bind(&params.webhook_url);
                query = query.bind(&params.decoration);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteNotifDiscordParams,
    ) -> Result<NotifDiscord, sqlx::Error> {
        sqlx::query_as::<_, NotifDiscord>(
            r#"
            UPDATE notif_discord
            SET
              webhook_url = ?,
              decoration = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .bind(&params.decoration)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateNotifDiscordParams,
    ) -> Result<NotifDiscord, sqlx::Error> {
        sqlx::query_as::<_, NotifDiscord>(
            r#"
            UPDATE notif_discord
            SET
              webhook_url = COALESCE(?, webhook_url),
              decoration = COALESCE(?, decoration)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.webhook_url)
        .bind(&params.decoration)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM notif_discord
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
