// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::policy::Policy;

#[derive(Debug, Clone, Default)]
pub struct PaginatePolicyParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationPolicyMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedPolicy {
    pub meta: PaginationPolicyMeta,
    pub data: Vec<Policy>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertPolicyParams {
    pub action: String,
    pub created_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwritePolicyParams {
    pub action: String,
    pub created_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdatePolicyParams {
    pub action: Option<String>,
    pub created_at: Option<i64>,
}

pub struct PolicyRepository {
    pool: sqlx::SqlitePool,
}

impl PolicyRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Policy>, sqlx::Error> {
        sqlx::query_as::<_, Policy>(r#"SELECT * FROM policy"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginatePolicyParams,
    ) -> Result<PaginatedPolicy, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM policy"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Policy>(
            r#"
            SELECT *
            FROM policy
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedPolicy {
            meta: PaginationPolicyMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Policy>, sqlx::Error> {
        sqlx::query_as::<_, Policy>(
            r#"
            SELECT *
            FROM policy
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertPolicyParams) -> Result<Policy, sqlx::Error> {
        sqlx::query_as::<_, Policy>(
            r#"
            INSERT INTO policy (action, created_at)
            VALUES (?, COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
        )
        .bind(&params.action)
        .bind(&params.created_at)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertPolicyParams>,
    ) -> Result<Vec<Policy>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 2usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 2usize;
                let placeholders = vec![
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "policy",
                "action, created_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Policy>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.action);
                query = query.bind(&params.created_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwritePolicyParams,
    ) -> Result<Policy, sqlx::Error> {
        sqlx::query_as::<_, Policy>(
            r#"
            UPDATE policy
            SET
              action = ?,
              created_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.action)
        .bind(&params.created_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdatePolicyParams,
    ) -> Result<Policy, sqlx::Error> {
        sqlx::query_as::<_, Policy>(
            r#"
            UPDATE policy
            SET
              action = COALESCE(?, action),
              created_at = COALESCE(?, created_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.action)
        .bind(&params.created_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM policy
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
