// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::project_tags::ProjectTag;

#[derive(Debug, Clone, Default)]
pub struct PaginateProjectTagParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationProjectTagMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedProjectTag {
    pub meta: PaginationProjectTagMeta,
    pub data: Vec<ProjectTag>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertProjectTagParams {
    pub project_id: i64,
    pub tag_id: i64,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteProjectTagParams {
    pub project_id: i64,
    pub tag_id: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateProjectTagParams {
    pub project_id: Option<i64>,
    pub tag_id: Option<i64>,
}

pub struct ProjectTagRepository {
    pool: sqlx::SqlitePool,
}

impl ProjectTagRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<ProjectTag>, sqlx::Error> {
        sqlx::query_as::<_, ProjectTag>(r#"SELECT * FROM project_tags"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateProjectTagParams,
    ) -> Result<PaginatedProjectTag, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM project_tags"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, ProjectTag>(
            r#"
            SELECT *
            FROM project_tags
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedProjectTag {
            meta: PaginationProjectTagMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<ProjectTag>, sqlx::Error> {
        sqlx::query_as::<_, ProjectTag>(
            r#"
            SELECT *
            FROM project_tags
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertProjectTagParams) -> Result<ProjectTag, sqlx::Error> {
        sqlx::query_as::<_, ProjectTag>(
            r#"
            INSERT INTO project_tags (project_id, tag_id)
            VALUES (?, ?)
            RETURNING *
        "#,
        )
        .bind(&params.project_id)
        .bind(&params.tag_id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertProjectTagParams>,
    ) -> Result<Vec<ProjectTag>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 2usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 2usize;
                let placeholders = vec!["?".to_string(), "?".to_string()];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "project_tags",
                "project_id, tag_id",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, ProjectTag>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.project_id);
                query = query.bind(&params.tag_id);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteProjectTagParams,
    ) -> Result<ProjectTag, sqlx::Error> {
        sqlx::query_as::<_, ProjectTag>(
            r#"
            UPDATE project_tags
            SET
              project_id = ?,
              tag_id = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.project_id)
        .bind(&params.tag_id)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateProjectTagParams,
    ) -> Result<ProjectTag, sqlx::Error> {
        sqlx::query_as::<_, ProjectTag>(
            r#"
            UPDATE project_tags
            SET
              project_id = COALESCE(?, project_id),
              tag_id = COALESCE(?, tag_id)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.project_id)
        .bind(&params.tag_id)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM project_tags
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
