// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::projects::Project;

#[derive(Debug, Clone, Default)]
pub struct PaginateProjectParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationProjectMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedProject {
    pub meta: PaginationProjectMeta,
    pub data: Vec<Project>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertProjectParams {
    pub name: String,
    pub description: Option<String>,
    pub env_var: Option<String>,
    pub organization_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteProjectParams {
    pub name: String,
    pub description: Option<String>,
    pub env_var: String,
    pub organization_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateProjectParams {
    pub name: Option<String>,
    pub description: Option<String>,
    pub env_var: Option<String>,
    pub organization_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct ProjectRepository {
    pool: sqlx::SqlitePool,
}

impl ProjectRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Project>, sqlx::Error> {
        sqlx::query_as::<_, Project>(r#"SELECT * FROM projects"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateProjectParams,
    ) -> Result<PaginatedProject, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM projects"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Project>(
            r#"
            SELECT *
            FROM projects
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedProject {
            meta: PaginationProjectMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Project>, sqlx::Error> {
        sqlx::query_as::<_, Project>(
            r#"
            SELECT *
            FROM projects
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertProjectParams) -> Result<Project, sqlx::Error> {
        sqlx::query_as::<
            _,
            Project,
        >(
                r#"
            INSERT INTO projects (name, description, env_var, organization_id, created_at, updated_at)
            VALUES (?, ?, COALESCE(?, ''), ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.description)
            .bind(&params.env_var)
            .bind(&params.organization_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertProjectParams>,
    ) -> Result<Vec<Project>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 6usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 6usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "''"),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "projects",
                "name, description, env_var, organization_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Project>(&sql);
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.description);
                query = query.bind(&params.env_var);
                query = query.bind(&params.organization_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteProjectParams,
    ) -> Result<Project, sqlx::Error> {
        sqlx::query_as::<_, Project>(
            r#"
            UPDATE projects
            SET
              name = ?,
              description = ?,
              env_var = ?,
              organization_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.env_var)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateProjectParams,
    ) -> Result<Project, sqlx::Error> {
        sqlx::query_as::<_, Project>(
            r#"
            UPDATE projects
            SET
              name = COALESCE(?, name),
              description = COALESCE(?, description),
              env_var = COALESCE(?, env_var),
              organization_id = COALESCE(?, organization_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.env_var)
        .bind(&params.organization_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM projects
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
