// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::rollbacks::Rollback;

#[derive(Debug, Clone, Default)]
pub struct PaginateRollbackParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationRollbackMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedRollback {
    pub meta: PaginationRollbackMeta,
    pub data: Vec<Rollback>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertRollbackParams {
    pub deployment_id: i64,
    pub version: Option<i64>,
    pub image: Option<String>,
    pub full_context: Option<String>,
    pub created_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteRollbackParams {
    pub deployment_id: i64,
    pub version: i64,
    pub image: Option<String>,
    pub full_context: Option<String>,
    pub created_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateRollbackParams {
    pub deployment_id: Option<i64>,
    pub version: Option<i64>,
    pub image: Option<String>,
    pub full_context: Option<String>,
    pub created_at: Option<i64>,
}

pub struct RollbackRepository {
    pool: sqlx::SqlitePool,
}

impl RollbackRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Rollback>, sqlx::Error> {
        sqlx::query_as::<_, Rollback>(r#"SELECT * FROM rollbacks"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateRollbackParams,
    ) -> Result<PaginatedRollback, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM rollbacks"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Rollback>(
            r#"
            SELECT *
            FROM rollbacks
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedRollback {
            meta: PaginationRollbackMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Rollback>, sqlx::Error> {
        sqlx::query_as::<_, Rollback>(
            r#"
            SELECT *
            FROM rollbacks
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertRollbackParams) -> Result<Rollback, sqlx::Error> {
        sqlx::query_as::<_, Rollback>(
            r#"
            INSERT INTO rollbacks (deployment_id, version, image, full_context, created_at)
            VALUES (?, COALESCE(?, 1), ?, ?, COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
        )
        .bind(&params.deployment_id)
        .bind(&params.version)
        .bind(&params.image)
        .bind(&params.full_context)
        .bind(&params.created_at)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertRollbackParams>,
    ) -> Result<Vec<Rollback>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 5usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 5usize;
                let placeholders = vec![
                    "?".to_string(),
                    format!("COALESCE(?, {})", "1"),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "rollbacks",
                "deployment_id, version, image, full_context, created_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Rollback>(&sql);
            for params in chunk {
                query = query.bind(&params.deployment_id);
                query = query.bind(&params.version);
                query = query.bind(&params.image);
                query = query.bind(&params.full_context);
                query = query.bind(&params.created_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteRollbackParams,
    ) -> Result<Rollback, sqlx::Error> {
        sqlx::query_as::<_, Rollback>(
            r#"
            UPDATE rollbacks
            SET
              deployment_id = ?,
              version = ?,
              image = ?,
              full_context = ?,
              created_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.deployment_id)
        .bind(&params.version)
        .bind(&params.image)
        .bind(&params.full_context)
        .bind(&params.created_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateRollbackParams,
    ) -> Result<Rollback, sqlx::Error> {
        sqlx::query_as::<_, Rollback>(
            r#"
            UPDATE rollbacks
            SET
              deployment_id = COALESCE(?, deployment_id),
              version = COALESCE(?, version),
              image = COALESCE(?, image),
              full_context = COALESCE(?, full_context),
              created_at = COALESCE(?, created_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.deployment_id)
        .bind(&params.version)
        .bind(&params.image)
        .bind(&params.full_context)
        .bind(&params.created_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM rollbacks
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
