// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::servers::Server;

#[derive(Debug, Clone, Default)]
pub struct PaginateServerParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationServerMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedServer {
    pub meta: PaginationServerMeta,
    pub data: Vec<Server>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertServerParams {
    pub name: String,
    pub description: Option<String>,
    pub ip_address: String,
    pub port: Option<i64>,
    pub username: Option<String>,
    pub app_name: String,
    pub server_status: Option<String>,
    pub server_type: Option<String>,
    pub enable_docker_cleanup: Option<i64>,
    pub log_cleanup_cron: Option<String>,
    pub command: Option<String>,
    pub metrics_config: Option<String>,
    pub ssh_key_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    pub build_memory_limit: Option<String>,
    pub build_cpu_limit: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteServerParams {
    pub name: String,
    pub description: Option<String>,
    pub ip_address: String,
    pub port: i64,
    pub username: String,
    pub app_name: String,
    pub server_status: String,
    pub server_type: String,
    pub enable_docker_cleanup: i64,
    pub log_cleanup_cron: Option<String>,
    pub command: String,
    pub metrics_config: String,
    pub ssh_key_id: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
    pub build_memory_limit: Option<String>,
    pub build_cpu_limit: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateServerParams {
    pub name: Option<String>,
    pub description: Option<String>,
    pub ip_address: Option<String>,
    pub port: Option<i64>,
    pub username: Option<String>,
    pub app_name: Option<String>,
    pub server_status: Option<String>,
    pub server_type: Option<String>,
    pub enable_docker_cleanup: Option<i64>,
    pub log_cleanup_cron: Option<String>,
    pub command: Option<String>,
    pub metrics_config: Option<String>,
    pub ssh_key_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    pub build_memory_limit: Option<String>,
    pub build_cpu_limit: Option<String>,
}

pub struct ServerRepository {
    pool: sqlx::SqlitePool,
}

impl ServerRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<Server>, sqlx::Error> {
        sqlx::query_as::<_, Server>(r#"SELECT * FROM servers"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateServerParams,
    ) -> Result<PaginatedServer, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM servers"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, Server>(
            r#"
            SELECT *
            FROM servers
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedServer {
            meta: PaginationServerMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<Server>, sqlx::Error> {
        sqlx::query_as::<_, Server>(
            r#"
            SELECT *
            FROM servers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertServerParams) -> Result<Server, sqlx::Error> {
        sqlx::query_as::<
            _,
            Server,
        >(
                r#"
            INSERT INTO servers (name, description, ip_address, port, username, app_name, server_status, server_type, enable_docker_cleanup, log_cleanup_cron, command, metrics_config, ssh_key_id, created_at, updated_at, build_memory_limit, build_cpu_limit)
            VALUES (?, ?, ?, COALESCE(?, 22), COALESCE(?, 'root'), ?, COALESCE(?, 'ACTIVE'), COALESCE(?, 'DEPLOY'), COALESCE(?, 0), COALESCE(?, '0 0 * * *'), COALESCE(?, ''), COALESCE(?, '{}'), ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')), ?, ?)
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.description)
            .bind(&params.ip_address)
            .bind(&params.port)
            .bind(&params.username)
            .bind(&params.app_name)
            .bind(&params.server_status)
            .bind(&params.server_type)
            .bind(&params.enable_docker_cleanup)
            .bind(&params.log_cleanup_cron)
            .bind(&params.command)
            .bind(&params.metrics_config)
            .bind(&params.ssh_key_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .bind(&params.build_memory_limit)
            .bind(&params.build_cpu_limit)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertServerParams>,
    ) -> Result<Vec<Server>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 17usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 17usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "22"),
                    format!("COALESCE(?, {})", "'root'"),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'ACTIVE'"),
                    format!("COALESCE(?, {})", "'DEPLOY'"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "'0 0 * * *'"),
                    format!("COALESCE(?, {})", "''"),
                    format!("COALESCE(?, {})", "'{}'"),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    "?".to_string(),
                    "?".to_string(),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "servers",
                "name, description, ip_address, port, username, app_name, server_status, server_type, enable_docker_cleanup, log_cleanup_cron, command, metrics_config, ssh_key_id, created_at, updated_at, build_memory_limit, build_cpu_limit",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, Server>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.description);
                query = query.bind(&params.ip_address);
                query = query.bind(&params.port);
                query = query.bind(&params.username);
                query = query.bind(&params.app_name);
                query = query.bind(&params.server_status);
                query = query.bind(&params.server_type);
                query = query.bind(&params.enable_docker_cleanup);
                query = query.bind(&params.log_cleanup_cron);
                query = query.bind(&params.command);
                query = query.bind(&params.metrics_config);
                query = query.bind(&params.ssh_key_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
                query = query.bind(&params.build_memory_limit);
                query = query.bind(&params.build_cpu_limit);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteServerParams,
    ) -> Result<Server, sqlx::Error> {
        sqlx::query_as::<_, Server>(
            r#"
            UPDATE servers
            SET
              name = ?,
              description = ?,
              ip_address = ?,
              port = ?,
              username = ?,
              app_name = ?,
              server_status = ?,
              server_type = ?,
              enable_docker_cleanup = ?,
              log_cleanup_cron = ?,
              command = ?,
              metrics_config = ?,
              ssh_key_id = ?,
              created_at = ?,
              updated_at = ?,
              build_memory_limit = ?,
              build_cpu_limit = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.ip_address)
        .bind(&params.port)
        .bind(&params.username)
        .bind(&params.app_name)
        .bind(&params.server_status)
        .bind(&params.server_type)
        .bind(&params.enable_docker_cleanup)
        .bind(&params.log_cleanup_cron)
        .bind(&params.command)
        .bind(&params.metrics_config)
        .bind(&params.ssh_key_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(&params.build_memory_limit)
        .bind(&params.build_cpu_limit)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateServerParams,
    ) -> Result<Server, sqlx::Error> {
        sqlx::query_as::<_, Server>(
            r#"
            UPDATE servers
            SET
              name = COALESCE(?, name),
              description = COALESCE(?, description),
              ip_address = COALESCE(?, ip_address),
              port = COALESCE(?, port),
              username = COALESCE(?, username),
              app_name = COALESCE(?, app_name),
              server_status = COALESCE(?, server_status),
              server_type = COALESCE(?, server_type),
              enable_docker_cleanup = COALESCE(?, enable_docker_cleanup),
              log_cleanup_cron = COALESCE(?, log_cleanup_cron),
              command = COALESCE(?, command),
              metrics_config = COALESCE(?, metrics_config),
              ssh_key_id = COALESCE(?, ssh_key_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at),
              build_memory_limit = COALESCE(?, build_memory_limit),
              build_cpu_limit = COALESCE(?, build_cpu_limit)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.ip_address)
        .bind(&params.port)
        .bind(&params.username)
        .bind(&params.app_name)
        .bind(&params.server_status)
        .bind(&params.server_type)
        .bind(&params.enable_docker_cleanup)
        .bind(&params.log_cleanup_cron)
        .bind(&params.command)
        .bind(&params.metrics_config)
        .bind(&params.ssh_key_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(&params.build_memory_limit)
        .bind(&params.build_cpu_limit)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM servers
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
