// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::server_metrics::ServerMetric;

#[derive(Debug, Clone, Default)]
pub struct PaginateServerMetricParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationServerMetricMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedServerMetric {
    pub meta: PaginationServerMetricMeta,
    pub data: Vec<ServerMetric>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertServerMetricParams {
    pub cpu: f64,
    pub cpu_model: String,
    pub cpu_cores: i64,
    pub cpu_physical_cores: i64,
    pub cpu_speed: f64,
    pub os: String,
    pub distro: String,
    pub kernel: String,
    pub arch: String,
    pub mem_used: f64,
    pub mem_used_gb: f64,
    pub mem_total: f64,
    pub uptime: i64,
    pub disk_used: f64,
    pub total_disk: f64,
    pub network_in: f64,
    pub network_out: f64,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteServerMetricParams {
    pub cpu: f64,
    pub cpu_model: String,
    pub cpu_cores: i64,
    pub cpu_physical_cores: i64,
    pub cpu_speed: f64,
    pub os: String,
    pub distro: String,
    pub kernel: String,
    pub arch: String,
    pub mem_used: f64,
    pub mem_used_gb: f64,
    pub mem_total: f64,
    pub uptime: i64,
    pub disk_used: f64,
    pub total_disk: f64,
    pub network_in: f64,
    pub network_out: f64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateServerMetricParams {
    pub cpu: Option<f64>,
    pub cpu_model: Option<String>,
    pub cpu_cores: Option<i64>,
    pub cpu_physical_cores: Option<i64>,
    pub cpu_speed: Option<f64>,
    pub os: Option<String>,
    pub distro: Option<String>,
    pub kernel: Option<String>,
    pub arch: Option<String>,
    pub mem_used: Option<f64>,
    pub mem_used_gb: Option<f64>,
    pub mem_total: Option<f64>,
    pub uptime: Option<i64>,
    pub disk_used: Option<f64>,
    pub total_disk: Option<f64>,
    pub network_in: Option<f64>,
    pub network_out: Option<f64>,
}

pub struct ServerMetricRepository {
    pool: sqlx::SqlitePool,
}

impl ServerMetricRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<ServerMetric>, sqlx::Error> {
        sqlx::query_as::<_, ServerMetric>(r#"SELECT * FROM server_metrics"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateServerMetricParams,
    ) -> Result<PaginatedServerMetric, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM server_metrics"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, ServerMetric>(
            r#"
            SELECT *
            FROM server_metrics
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedServerMetric {
            meta: PaginationServerMetricMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, timestamp: i64) -> Result<Option<ServerMetric>, sqlx::Error> {
        sqlx::query_as::<_, ServerMetric>(
            r#"
            SELECT *
            FROM server_metrics
            WHERE timestamp = ?
        "#,
        )
        .bind(timestamp)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(
        &self,
        params: &InsertServerMetricParams,
    ) -> Result<ServerMetric, sqlx::Error> {
        sqlx::query_as::<
            _,
            ServerMetric,
        >(
                r#"
            INSERT INTO server_metrics (cpu, cpu_model, cpu_cores, cpu_physical_cores, cpu_speed, os, distro, kernel, arch, mem_used, mem_used_gb, mem_total, uptime, disk_used, total_disk, network_in, network_out)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING *
        "#,
            )
            .bind(&params.cpu)
            .bind(&params.cpu_model)
            .bind(&params.cpu_cores)
            .bind(&params.cpu_physical_cores)
            .bind(&params.cpu_speed)
            .bind(&params.os)
            .bind(&params.distro)
            .bind(&params.kernel)
            .bind(&params.arch)
            .bind(&params.mem_used)
            .bind(&params.mem_used_gb)
            .bind(&params.mem_total)
            .bind(&params.uptime)
            .bind(&params.disk_used)
            .bind(&params.total_disk)
            .bind(&params.network_in)
            .bind(&params.network_out)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertServerMetricParams>,
    ) -> Result<Vec<ServerMetric>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 17usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 17usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "server_metrics",
                "cpu, cpu_model, cpu_cores, cpu_physical_cores, cpu_speed, os, distro, kernel, arch, mem_used, mem_used_gb, mem_total, uptime, disk_used, total_disk, network_in, network_out",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, ServerMetric>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.cpu);
                query = query.bind(&params.cpu_model);
                query = query.bind(&params.cpu_cores);
                query = query.bind(&params.cpu_physical_cores);
                query = query.bind(&params.cpu_speed);
                query = query.bind(&params.os);
                query = query.bind(&params.distro);
                query = query.bind(&params.kernel);
                query = query.bind(&params.arch);
                query = query.bind(&params.mem_used);
                query = query.bind(&params.mem_used_gb);
                query = query.bind(&params.mem_total);
                query = query.bind(&params.uptime);
                query = query.bind(&params.disk_used);
                query = query.bind(&params.total_disk);
                query = query.bind(&params.network_in);
                query = query.bind(&params.network_out);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        timestamp: i64,
        params: &OverwriteServerMetricParams,
    ) -> Result<ServerMetric, sqlx::Error> {
        sqlx::query_as::<_, ServerMetric>(
            r#"
            UPDATE server_metrics
            SET
              cpu = ?,
              cpu_model = ?,
              cpu_cores = ?,
              cpu_physical_cores = ?,
              cpu_speed = ?,
              os = ?,
              distro = ?,
              kernel = ?,
              arch = ?,
              mem_used = ?,
              mem_used_gb = ?,
              mem_total = ?,
              uptime = ?,
              disk_used = ?,
              total_disk = ?,
              network_in = ?,
              network_out = ?
            WHERE timestamp = ?
            RETURNING *
        "#,
        )
        .bind(&params.cpu)
        .bind(&params.cpu_model)
        .bind(&params.cpu_cores)
        .bind(&params.cpu_physical_cores)
        .bind(&params.cpu_speed)
        .bind(&params.os)
        .bind(&params.distro)
        .bind(&params.kernel)
        .bind(&params.arch)
        .bind(&params.mem_used)
        .bind(&params.mem_used_gb)
        .bind(&params.mem_total)
        .bind(&params.uptime)
        .bind(&params.disk_used)
        .bind(&params.total_disk)
        .bind(&params.network_in)
        .bind(&params.network_out)
        .bind(timestamp)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        timestamp: i64,
        params: &UpdateServerMetricParams,
    ) -> Result<ServerMetric, sqlx::Error> {
        sqlx::query_as::<_, ServerMetric>(
            r#"
            UPDATE server_metrics
            SET
              cpu = COALESCE(?, cpu),
              cpu_model = COALESCE(?, cpu_model),
              cpu_cores = COALESCE(?, cpu_cores),
              cpu_physical_cores = COALESCE(?, cpu_physical_cores),
              cpu_speed = COALESCE(?, cpu_speed),
              os = COALESCE(?, os),
              distro = COALESCE(?, distro),
              kernel = COALESCE(?, kernel),
              arch = COALESCE(?, arch),
              mem_used = COALESCE(?, mem_used),
              mem_used_gb = COALESCE(?, mem_used_gb),
              mem_total = COALESCE(?, mem_total),
              uptime = COALESCE(?, uptime),
              disk_used = COALESCE(?, disk_used),
              total_disk = COALESCE(?, total_disk),
              network_in = COALESCE(?, network_in),
              network_out = COALESCE(?, network_out)
            WHERE timestamp = ?
            RETURNING *
        "#,
        )
        .bind(&params.cpu)
        .bind(&params.cpu_model)
        .bind(&params.cpu_cores)
        .bind(&params.cpu_physical_cores)
        .bind(&params.cpu_speed)
        .bind(&params.os)
        .bind(&params.distro)
        .bind(&params.kernel)
        .bind(&params.arch)
        .bind(&params.mem_used)
        .bind(&params.mem_used_gb)
        .bind(&params.mem_total)
        .bind(&params.uptime)
        .bind(&params.disk_used)
        .bind(&params.total_disk)
        .bind(&params.network_in)
        .bind(&params.network_out)
        .bind(timestamp)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, timestamp: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM server_metrics
            WHERE timestamp = ?
        "#,
        )
        .bind(timestamp)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
