// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::ssh_keys::SshKey;

#[derive(Debug, Clone, Default)]
pub struct PaginateSshKeyParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationSshKeyMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedSshKey {
    pub meta: PaginationSshKeyMeta,
    pub data: Vec<SshKey>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertSshKeyParams {
    pub name: String,
    pub description: Option<String>,
    pub private_key: Option<String>,
    pub public_key: String,
    pub last_used_at: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteSshKeyParams {
    pub name: String,
    pub description: Option<String>,
    pub private_key: String,
    pub public_key: String,
    pub last_used_at: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateSshKeyParams {
    pub name: Option<String>,
    pub description: Option<String>,
    pub private_key: Option<String>,
    pub public_key: Option<String>,
    pub last_used_at: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct SshKeyRepository {
    pool: sqlx::SqlitePool,
}

impl SshKeyRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<SshKey>, sqlx::Error> {
        sqlx::query_as::<_, SshKey>(r#"SELECT * FROM ssh_keys"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateSshKeyParams,
    ) -> Result<PaginatedSshKey, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM ssh_keys"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, SshKey>(
            r#"
            SELECT *
            FROM ssh_keys
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedSshKey {
            meta: PaginationSshKeyMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<SshKey>, sqlx::Error> {
        sqlx::query_as::<_, SshKey>(
            r#"
            SELECT *
            FROM ssh_keys
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertSshKeyParams) -> Result<SshKey, sqlx::Error> {
        sqlx::query_as::<
            _,
            SshKey,
        >(
                r#"
            INSERT INTO ssh_keys (name, description, private_key, public_key, last_used_at, created_at, updated_at)
            VALUES (?, ?, COALESCE(?, ''), ?, ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.name)
            .bind(&params.description)
            .bind(&params.private_key)
            .bind(&params.public_key)
            .bind(&params.last_used_at)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertSshKeyParams>,
    ) -> Result<Vec<SshKey>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 7usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 7usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "''"),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "ssh_keys",
                "name, description, private_key, public_key, last_used_at, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, SshKey>(&sql);
            for params in chunk {
                query = query.bind(&params.name);
                query = query.bind(&params.description);
                query = query.bind(&params.private_key);
                query = query.bind(&params.public_key);
                query = query.bind(&params.last_used_at);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteSshKeyParams,
    ) -> Result<SshKey, sqlx::Error> {
        sqlx::query_as::<_, SshKey>(
            r#"
            UPDATE ssh_keys
            SET
              name = ?,
              description = ?,
              private_key = ?,
              public_key = ?,
              last_used_at = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.private_key)
        .bind(&params.public_key)
        .bind(&params.last_used_at)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(
        &self,
        id: i64,
        params: &UpdateSshKeyParams,
    ) -> Result<SshKey, sqlx::Error> {
        sqlx::query_as::<_, SshKey>(
            r#"
            UPDATE ssh_keys
            SET
              name = COALESCE(?, name),
              description = COALESCE(?, description),
              private_key = COALESCE(?, private_key),
              public_key = COALESCE(?, public_key),
              last_used_at = COALESCE(?, last_used_at),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.name)
        .bind(&params.description)
        .bind(&params.private_key)
        .bind(&params.public_key)
        .bind(&params.last_used_at)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM ssh_keys
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
