// Auto-generated by sqlx-gen. Do not edit.

use crate::db::models::users::User;

#[derive(Debug, Clone, Default)]
pub struct PaginateUserParams {
    pub page: i64,
    pub per_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginationUserMeta {
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
    pub first_page: i64,
}

#[derive(Debug, Clone)]
pub struct PaginatedUser {
    pub meta: PaginationUserMeta,
    pub data: Vec<User>,
}

#[derive(Debug, Clone, Default)]
pub struct InsertUserParams {
    pub email: Option<String>,
    pub last_name: Option<String>,
    pub first_name: Option<String>,
    pub avatar: String,
    pub role: Option<String>,
    pub about_me: Option<String>,
    pub password: String,
    pub is_email_verify: Option<i64>,
    pub email_verify_at: Option<i64>,
    pub two_factor_enable: Option<i64>,
    pub is_registered: Option<i64>,
    pub added_by: Option<i64>,
    pub group_id: i64,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Debug, Clone, Default)]
pub struct OverwriteUserParams {
    pub email: Option<String>,
    pub last_name: Option<String>,
    pub first_name: Option<String>,
    pub avatar: String,
    pub role: Option<String>,
    pub about_me: Option<String>,
    pub password: String,
    pub is_email_verify: Option<i64>,
    pub email_verify_at: Option<i64>,
    pub two_factor_enable: Option<i64>,
    pub is_registered: i64,
    pub added_by: Option<i64>,
    pub group_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateUserParams {
    pub email: Option<String>,
    pub last_name: Option<String>,
    pub first_name: Option<String>,
    pub avatar: Option<String>,
    pub role: Option<String>,
    pub about_me: Option<String>,
    pub password: Option<String>,
    pub is_email_verify: Option<i64>,
    pub email_verify_at: Option<i64>,
    pub two_factor_enable: Option<i64>,
    pub is_registered: Option<i64>,
    pub added_by: Option<i64>,
    pub group_id: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
}

pub struct UserRepository {
    pool: sqlx::SqlitePool,
}

impl UserRepository {
    pub fn new(pool: sqlx::SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn get_all(&self) -> Result<Vec<User>, sqlx::Error> {
        sqlx::query_as::<_, User>(r#"SELECT * FROM users"#)
            .fetch_all(&self.pool)
            .await
    }

    pub async fn paginate(
        &self,
        params: &PaginateUserParams,
    ) -> Result<PaginatedUser, sqlx::Error> {
        let total: i64 = sqlx::query_scalar(r#"SELECT COUNT(*) FROM users"#)
            .fetch_one(&self.pool)
            .await?;

        let per_page = params.per_page;
        let current_page = params.page;
        let last_page = (total + per_page - 1) / per_page;
        let offset = (current_page - 1) * per_page;

        let data = sqlx::query_as::<_, User>(
            r#"
            SELECT *
            FROM users
            LIMIT ? OFFSET ?
        "#,
        )
        .bind(per_page)
        .bind(offset)
        .fetch_all(&self.pool)
        .await?;

        Ok(PaginatedUser {
            meta: PaginationUserMeta {
                total,
                per_page,
                current_page,
                last_page,
                first_page: 1,
            },
            data,
        })
    }

    pub async fn get(&self, id: i64) -> Result<Option<User>, sqlx::Error> {
        sqlx::query_as::<_, User>(
            r#"
            SELECT *
            FROM users
            WHERE id = ?
        "#,
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
    }

    pub async fn insert(&self, params: &InsertUserParams) -> Result<User, sqlx::Error> {
        sqlx::query_as::<
            _,
            User,
        >(
                r#"
            INSERT INTO users (email, last_name, first_name, avatar, role, about_me, password, is_email_verify, email_verify_at, two_factor_enable, is_registered, added_by, group_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, COALESCE(?, 'OWNER'), ?, ?, COALESCE(?, 0), ?, COALESCE(?, 0), COALESCE(?, 0), COALESCE(?, NULL), ?, COALESCE(?, strftime('%s', 'now')), COALESCE(?, strftime('%s', 'now')))
            RETURNING *
        "#,
            )
            .bind(&params.email)
            .bind(&params.last_name)
            .bind(&params.first_name)
            .bind(&params.avatar)
            .bind(&params.role)
            .bind(&params.about_me)
            .bind(&params.password)
            .bind(&params.is_email_verify)
            .bind(&params.email_verify_at)
            .bind(&params.two_factor_enable)
            .bind(&params.is_registered)
            .bind(&params.added_by)
            .bind(&params.group_id)
            .bind(&params.created_at)
            .bind(&params.updated_at)
            .fetch_one(&self.pool)
            .await
    }

    pub async fn insert_many_transactionally(
        &self,
        entries: Vec<InsertUserParams>,
    ) -> Result<Vec<User>, sqlx::Error> {
        if entries.is_empty() {
            return Ok(Vec::new());
        }
        let mut tx = self.pool.begin().await?;

        let mut all_results = Vec::with_capacity(entries.len());
        let max_per_chunk = 65535 / 15usize;
        for chunk in entries.chunks(max_per_chunk) {
            let mut values_parts = Vec::with_capacity(chunk.len());
            for (row_idx, _) in chunk.iter().enumerate() {
                let base = row_idx * 15usize;
                let placeholders = vec![
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "'OWNER'"),
                    "?".to_string(),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "0"),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "0"),
                    format!("COALESCE(?, {})", "NULL"),
                    "?".to_string(),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                    format!("COALESCE(?, {})", "strftime('%s', 'now')"),
                ];
                values_parts.push(format!("({})", placeholders.join(", ")));
            }
            let sql = format!(
                "INSERT INTO {} ({})\nVALUES {}\nRETURNING *",
                "users",
                "email, last_name, first_name, avatar, role, about_me, password, is_email_verify, email_verify_at, two_factor_enable, is_registered, added_by, group_id, created_at, updated_at",
                values_parts.join(", ")
            );
            let mut query = sqlx::query_as::<_, User>(sqlx::AssertSqlSafe(&*sql));
            for params in chunk {
                query = query.bind(&params.email);
                query = query.bind(&params.last_name);
                query = query.bind(&params.first_name);
                query = query.bind(&params.avatar);
                query = query.bind(&params.role);
                query = query.bind(&params.about_me);
                query = query.bind(&params.password);
                query = query.bind(&params.is_email_verify);
                query = query.bind(&params.email_verify_at);
                query = query.bind(&params.two_factor_enable);
                query = query.bind(&params.is_registered);
                query = query.bind(&params.added_by);
                query = query.bind(&params.group_id);
                query = query.bind(&params.created_at);
                query = query.bind(&params.updated_at);
            }
            let rows = query.fetch_all(&mut *tx).await?;
            all_results.extend(rows);
        }
        tx.commit().await?;

        Ok(all_results)
    }

    pub async fn overwrite(
        &self,
        id: i64,
        params: &OverwriteUserParams,
    ) -> Result<User, sqlx::Error> {
        sqlx::query_as::<_, User>(
            r#"
            UPDATE users
            SET
              email = ?,
              last_name = ?,
              first_name = ?,
              avatar = ?,
              role = ?,
              about_me = ?,
              password = ?,
              is_email_verify = ?,
              email_verify_at = ?,
              two_factor_enable = ?,
              is_registered = ?,
              added_by = ?,
              group_id = ?,
              created_at = ?,
              updated_at = ?
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.email)
        .bind(&params.last_name)
        .bind(&params.first_name)
        .bind(&params.avatar)
        .bind(&params.role)
        .bind(&params.about_me)
        .bind(&params.password)
        .bind(&params.is_email_verify)
        .bind(&params.email_verify_at)
        .bind(&params.two_factor_enable)
        .bind(&params.is_registered)
        .bind(&params.added_by)
        .bind(&params.group_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn update(&self, id: i64, params: &UpdateUserParams) -> Result<User, sqlx::Error> {
        sqlx::query_as::<_, User>(
            r#"
            UPDATE users
            SET
              email = COALESCE(?, email),
              last_name = COALESCE(?, last_name),
              first_name = COALESCE(?, first_name),
              avatar = COALESCE(?, avatar),
              role = COALESCE(?, role),
              about_me = COALESCE(?, about_me),
              password = COALESCE(?, password),
              is_email_verify = COALESCE(?, is_email_verify),
              email_verify_at = COALESCE(?, email_verify_at),
              two_factor_enable = COALESCE(?, two_factor_enable),
              is_registered = COALESCE(?, is_registered),
              added_by = COALESCE(?, added_by),
              group_id = COALESCE(?, group_id),
              created_at = COALESCE(?, created_at),
              updated_at = COALESCE(?, updated_at)
            WHERE id = ?
            RETURNING *
        "#,
        )
        .bind(&params.email)
        .bind(&params.last_name)
        .bind(&params.first_name)
        .bind(&params.avatar)
        .bind(&params.role)
        .bind(&params.about_me)
        .bind(&params.password)
        .bind(&params.is_email_verify)
        .bind(&params.email_verify_at)
        .bind(&params.two_factor_enable)
        .bind(&params.is_registered)
        .bind(&params.added_by)
        .bind(&params.group_id)
        .bind(&params.created_at)
        .bind(&params.updated_at)
        .bind(id)
        .fetch_one(&self.pool)
        .await
    }

    pub async fn delete(&self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"
            DELETE FROM users
            WHERE id = ?
        "#,
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}
