// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "bitbucket_providers")]
pub struct BitbucketProvider {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bitbucket_username: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bitbucket_email: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub app_password: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub api_token: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bitbucket_workspace_name: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub git_provider_id: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
