// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "jwt_tokens")]
pub struct JwtToken {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub jti: String,
    #[sqlx_gen(sql_type = "jwt_tokens_role_enum")]
    pub role: String,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub user_id: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "0")]
    pub is_blacklist: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub blacklist_at: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub expired_at: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub created_at: i64,
    #[sqlx_gen(sql_type = "INTEGER", column_default = "strftime('%s', 'now')")]
    pub updated_at: i64,
}
