// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "notif_telegram")]
pub struct NotifTelegram {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub bot_token: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub chat_id: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub message_thread_id: Option<String>,
}
